### ISSUE TITLE
Define futureStates at runtime

### ISSUE THREAD

**Issue by varunmc** [christopherthielen/ui-router-extras#111]
In the first block [here](http://christopherthielen.github.io/ui-router-extras/#/future) you mentioned:

> FutureStates are declared at config time (or optionally at runtime), and replaced with a full UI-Router state when navigated to.

How did we register a futureState at runtime?

**Comment by hasanlussa** [comment]
You can register a futurestate in `runtime`. But you cannot register `state factory` on runtime. 
here is my working sample

on my controller
```js
angular.controller(['$futureState', function($futureState){
..
$futureState.futureState({
    stateName : '<your fancy state name>' // make sure the parent exist,
    type : '<valid & registered state factory>', // make sure you already created & registered state factory on config phase
    url : '/<state url>',
    ...
});
// check it
console.log($futureState.get());
..
```

@FrontierPsychiatrist
