### ISSUE TITLE
sticky: true and re-evaluating resolve objects

### ISSUE THREAD

**Issue by kasperlewau** [christopherthielen/ui-router-extras#114]
In our application, we've setup a wrapping API around ct-ui-router-extras where we enforce `sticky: true` on all states that are not considered a dialog/modal state (where we set `sticky: false`). 

At some point we realised that this has introduced a bug pertaining to resolve objects not re-evaluating when transitioning between `sticky: true` states the second, third (etc.) time around. 

```js
$stateProvider.state('base', {
  url: '/base'
});

$stateProvider.state('base.child1', {
  sticky: true, 
  url: '/child_one/:name',
  resolve: {
    hello: function ($stateParams) {
      return 'Aloha, ' + $stateParams.name;
    }
  },
  controller: function ($scope, hello) {
    console.log(hello);
  }
});

$stateProvider.state('base.child2', {
  sticky: true,
  url: '/child_two',
  controller: function ($scope, $state) {
    $scope.transition = function (name) {
      $state.go('base.child1', { name: name });
    };
  }
});
```

```html
<div>
  <button ng-click="transition('Kasper')">
  <button ng-click="transition('Glenn')">
</div>
```

With the above in mind, we are experiencing the following: 

* Boot up the application, and go to `base.child2` state. 
* Click the first button -> Transition to `base.child1` state. 
  * In the console, we will now see the following output: `Aloha, Kasper`.
* Go back to `base.child2` state. 
* Click the second button -> Transition to `base.child1` state. 
  * In the console, we will (yet again) see the following output: `Aloha, Kasper`.

At the last step, we are expecting to see `Aloha, Glenn` - but the case is not so. 

We are running the following setup: 

`angular 1.2.26`
`ui-router 0.2.11`
`ct-ui-router-extras 0.0.11`

Are we missing something in how sticky states work with resolve objects, or is this an actual bug? 

I'm very sorry for the lack of a working live example of the problem we're encountering, but I have yet to be able to create a working jsBin. I'll update this post if I manage to set one up - but running the code above (locally) with the specified libraries I keep seeing `$stateParams.name` resolving to the first value it encountered. 

From what I gather, this could have something to do with [getStickyTransitionType#319](https://github.com/christopherthielen/ui-router-extras/blob/master/release/ct-ui-router-extras.js#L319) and/or [getEnterTransition#333](https://github.com/christopherthielen/ui-router-extras/blob/master/release/ct-ui-router-extras.js#L333), but I might just be taking a stab in the dark. 

Lastly, if I hardcode the [enterTrans variable#L413](https://github.com/christopherthielen/ui-router-extras/blob/master/release/ct-ui-router-extras.js#L333) to `"enter"` - we get the expected behaviour of `$stateParams.name` resolving to the correct value on each consecutive transition to the affected `$state`.

**Comment by christopherthielen** [comment]
@kasperlewau I'll be closing this soon due to inactivity, unless you have further comments.

**Comment by christopherthielen** [comment]
cc: @tregusti  @mhenrixon I'll be closing this soon due to inactivity, unless you have further comments.

**Comment by danielmeng07** [comment]
I'm having some trouble understanding the intended behavior. One of our states contains a resolve, 
but whenever I switch to the modal state, Angular throws an error: 
`Error: $injector:unpr Unknown Provider` 

It seems the resolve variable got "disconnected". I'm currently using sticky states, and it seems to prevent the `onExit` callback from running, but the resolve variable still gets lost. Is this suppose to happen?
