### ISSUE TITLE
"$stateNotFound" debug logging trying to load Future State for the first time

### ISSUE THREAD

**Issue by antch** [christopherthielen/ui-router-extras#116]
I recently incorporated future states into my application, and the first time I attempt to navigate to the future state I get a log message in the console that a "$stateNotFound" event was broadcast, along with some debugging information.  However, the state transition does appear to work properly.  It is not desirable to have this information logged to the console, which gives the appearance that an error has occurred with the application.  With that said I'm not sure if there is any way to avoid this logging with better/different code, or if an enhancement to `ui-router-extras` may be able to take care of it.

I created a simplified Plunkr that demonstrates this -- just click on the HTML "Edit" link and observe the browser console:

http://plnkr.co/edit/KC9Hak8LOx6YmfxDTEcP?p=preview

Just for a little background, there are two main requirements that led me to the solution above:
1. Ability to package state definitions in a separate JavaScript file/module (the real application uses `RequireJS` for this.
2. Ability to inject runtime dependencies (services, etc) into state `resolve` functions.

**Comment by christopherthielen** [comment]
That's simply a debug-level message.  Disable debug logging using `$logProvider.debugEnabled(false);`

https://docs.angularjs.org/api/ng/provider/$logProvider
