### ISSUE TITLE
Stack of previoius states

### ISSUE THREAD

**Issue by stevehenry13** [christopherthielen/ui-router-extras#118]
Would it be possible for a stack of previous states, so that calling previousState.go() multiple times goes down the stack, instead of flipping back and forth between the two most recent?

**Comment by christopherthielen** [comment]
Certainly it is possible.  However, I am not planning on enhancing $previousStates, as I think its functionality is trivial to roll-your-own and the implementation/api is just "meh".  Have a look at @nateabele's first pass at a $history service, which might be a better place to put that effort:
http://plnkr.co/edit/DJH6mQUCbTFfSbdCBYUo?p=preview
