### ISSUE TITLE
onEnter and onExit callbacks do not fire on re-visits to sticky state

### ISSUE THREAD

**Issue by FieldMarshallVague** [christopherthielen/ui-router-extras#122]
This is similar to #114 (which deals with resolve objects):  neither onEnter or onExit callbacks are firing on sticky states once they have been cached/rendered.  

In my case, I change a property on a service when a particular state is entered/exited.  With sticky:true, these only fire the first time I visit the state and subsequently the property doesn't change.

I realise the fate of this issue might be linked to #114, but I can understand resolve objects being cached while I don't see any sense in these callbacks being effectively disabled.

p.s.  this is a really useful repo, great work, Chris et al!

**Comment by michahell** [comment]
If you want to know this within your controller, the follow works (but is quite some bloat tbh):
```javascript
$scope.$on('$stateChangeSuccess', function(event, toState, toParams, fromState, fromParams, options) { 
      if(toState.name === 'overview') {
        console.log('state change success overview.js...');
      }
    });
```
Is there a nicer way to do this?
Can we use the onReactivate callbacks in the state definition to call a controller method? that would be way nicer.
