### ISSUE TITLE
(Previous State) Error: Cannot transition to abstract state '[object Object]'

### ISSUE THREAD

**Issue by eseceve** [christopherthielen/ui-router-extras#123]
If you load this http://christopherthielen.github.io/ui-router-extras/example/stickymodal/index.html#/modal1 and then close the modal you get this error:

```
Error: Cannot transition to abstract state '[object Object]'
    at Object.transitionTo (http://christopherthielen.github.io/ui-router-extras/lib/angular-ui-router.js:3077:39)
    at Object.$state.transitionTo (http://christopherthielen.github.io/ui-router-extras/lib/ct-ui-router-extras.js:136:34)
    at Object.$state.transitionTo (http://christopherthielen.github.io/ui-router-extras/lib/ct-ui-router-extras.js:929:55)
    at Object.$state.transitionTo (http://christopherthielen.github.io/ui-router-extras/lib/ct-ui-router-extras.js:1415:48)
    at Object.go (http://christopherthielen.github.io/ui-router-extras/lib/angular-ui-router.js:3007:21)
    at Object.$previousState.go (http://christopherthielen.github.io/ui-router-extras/lib/ct-ui-router-extras.js:1329:25)
    at Scope.$scope.close (http://christopherthielen.github.io/ui-router-extras/example/stickymodal/app.js:64:28)
    at http://christopherthielen.github.io/ui-router-extras/lib/angular.js:10694:21
    at http://christopherthielen.github.io/ui-router-extras/lib/angular.js:18882:17
    at Scope.$eval (http://christopherthielen.github.io/ui-router-extras/lib/angular.js:12556:28)
```

**Comment by matthewharwood** [comment]
I'm not sure but I'd guess that this error is created when there is not previousstate .memo set

for instance: 
www.mysite.com/things/thingid  (lets pretend that the /thingid state has a button in the view and this button has a previous state trigger set to it.

If a user was to just jump right to www.mysite.com/things/thingid from, say the url bar? there wouldn't have been a previous state set.  Therefore, this abstract state [obj obj] error is thrown. 

I haven't written a solution for this but I would create a fallback to history.back() maybe?  My Javascript/angular isnt that great but I think you should write a decorator and create a fall back... if this is a good solution could you post me a gist of your decorator cuz I need it too.

**Comment by christopherthielen** [comment]
`.memo()` is supposed to allow a default previous state to be applied if this is the first transition.  However, it never got tested and is broken.   The fix for the demo is to write `$previousState.memo("modalInvoker", "top")`, but this doesn't work because of the bug in .memo which is registering the root state ("") as the previous state.  The fix for .memo is to check if the previous state is is navigable `if (state.navigable)`

**Comment by astyfx** [comment]
There is any chance of set default state if transition to abstract state?

ex) $previousState.memo("modalInvoker", default_state_go="main")

main is registered in ui-router state not $previousState.memo

**Comment by astyfx** [comment]
### in Modal init
`$previousState.memo('caller', 'main');`


### in ct-ui-router-extras.js
```
var $previousState = {
    get: function (memoName) {
        return memoName ? memos[memoName] : previous;
    },
    go: function (memoName, options) {
        var to = $previousState.get(memoName);
        if(to.state.abstract)
            return $state.go(to.default.state, to.default.params, options);
        else
            return $state.go(to.state, to.params, options);
    },
    memo: function (memoName, defaultStateName, defaultStateParams) {
        memos[memoName] = previous || {state: $state.get(defaultStateName), params: defaultStateParams};
        memos[memoName].default = {state: $state.get(defaultStateName), params: defaultStateParams};
    },
    forget: function (memoName) {
        delete memos[memoName];
    }
};
```

temporal fix for this bug. using @christopherthielen answered plunker's extras.js in #139
