### ISSUE TITLE
Reactivate state reloads the controller for the view

### ISSUE THREAD

**Issue by Bolza** [christopherthielen/ui-router-extras#132]
As for object of the issue i can see from the debugging info that the state view is correctly flagged as inactive when exiting. But then, when we re-enter that state the controller is reloaded. 

Transition Modal1 --> Modal2
Seems fine and:
inactive states:  ["top.main.lobby", "top.main", "top.modal.example1"]

Here's the complete trace
```
Current transition:  top.modal.example1: {}:  -> top.modal.example2: {}
Before transition, inactives are:   :  ["top.main.lobby", "top.main"]
After transition,  inactives will be:  ["top.main.lobby", "top.main", "top.main.lobby", "top.main", "top.modal.example1"]
Transition will exit:   ["(top)", "(top.modal)", "INACTIVATE: top.modal.example1"]
Transition will enter:  ["(top)", "(top.modal)", "ENTER: top.modal.example2"]
SurrogateFromPath:  ["top", "top.modal", "inactivate:top.modal.example1"]
SurrogateToPath:    ["top", "top.modal", "top.modal.example2"]

modal.example.controller.js:10 ---> ModalExampleCtrl INIT on STATE: top.modal.example2

Current state: top.modal.example2, inactive states:  ["top.main.lobby", "top.main", "top.modal.example1"]
Views: (__inactives.locals: '@top.main' (top.main.lobby), 'main@top' (top.main), 'content@top.modal' (top.modal.example1)) / (root.locals) / (top.locals: 'top@' (top)) / (top.locals: 'top@' (top)) / (top.modal.locals: 'modal@top' (top.modal)) / (top.modal.example2.locals: 'content@top.modal' (top.modal.example2))
```

Then Modal2 --> Modal1
I expect the Modal1 to resume and not reload the controller.
But even if the debug says SurrogateToPath:    ["top", "top.modal", "reactivate_phase1:top.modal.example1", "reactivate_phase2:top.modal.example1"]
I still have the Modal1 controller reloaded.

Here's the complete trace:
```
Current transition:  top.modal.example2: {}:  -> top.modal.example1: {}
Before transition, inactives are:   :  ["top.main.lobby", "top.main", "top.modal.example1"]
After transition,  inactives will be:  ["top.main.lobby", "top.main", "top.main.lobby", "top.main", "top.modal.example2"]
Transition will exit:   ["(top)", "(top.modal)", "INACTIVATE: top.modal.example2"]
Transition will enter:  ["(top)", "(top.modal)", "REACTIVATE: top.modal.example1"]
SurrogateFromPath:  ["top", "top.modal", "reactivate_phase1:top.modal.example1", "inactivate:top.modal.example2"]
SurrogateToPath:    ["top", "top.modal", "reactivate_phase1:top.modal.example1", "reactivate_phase2:top.modal.example1"]

modal.example.controller.js:10 ---> ModalExampleCtrl INIT on STATE: top.modal.example1

Current state: top.modal.example1, inactive states:  ["top.main.lobby", "top.main", "top.modal.example2"]
Views: (__inactives.locals: '@top.main' (top.main.lobby), 'main@top' (top.main), 'content@top.modal' (top.modal.example2)) / (root.locals) / (top.locals: 'top@' (top)) / (top.locals: 'top@' (top)) / (top.modal.locals: 'modal@top' (top.modal)) / (top.modal.example1.locals: 'content@top.modal' (top.modal.example1))
```

I have this structure
```
(top:sticky)

-> (top.main:sticky)   
--> top.main.lobby  

-> (top.modal)
--> top.modal.example1:sticky   
--> top.modal.example1:sticky 
```

Is this a bug? Or it's just meant to be so?
On "top.main.lobby" everything works fine, the controller is not reloaded.

PS: Anyway great job with this library.

**Comment by christopherthielen** [comment]
Hi, that looks like a bug.  Can you provide a plunkr?

**Comment by christopherthielen** [comment]
@Bolza can you provide a plunkr?  Also, this may be related to #131, please check that bug out.

**Comment by Bolza** [comment]
I'll work on a Plunkr tomorrow but in the meantime i can say my use case is slightly different than #131 because my flow is like:
parent1.child1 -> parent2.child1 -> parent2.child2 -> parent2.child1 -> parent1.child1

and is the second transition to parent2.child1 to reload the controller, that is a transition between states with the same parent, while the last trasition correctly restores the sticky state of parent1.child1.
Anyway it could still be the same source of the bug.

**Comment by christopherthielen** [comment]
@Bolza thanks for the clarification

**Comment by Bolza** [comment]
Hi this is the plunkr: http://plnkr.co/edit/Og01IN
To reproduce the bug use the buttons to
open modal 1 -> open modal 2 -> close modal 

As you can see the modal1 is reloaded.

**Comment by christopherthielen** [comment]
@Bolza you are re-using the same view name.  Sticky states works by retaining the DOM. By re-using the `content` view for both modals, you are clobbering modal1's DOM with modal2's (and vice versa)

Here it is working with separate named views: http://plnkr.co/edit/r6O3Ak?p=preview

**Comment by Bolza** [comment]
Oh i see, my bad, thanks for the tip.
Unfortunately this makes my use-case almost impossible to solve using sticky states, because i could need to keep stuck an unknown number of views. And i don't want to add a new ui-view and for each one.

I wonder if won't be possible (and very powerful) to store the sticky states view not by view name but by state.name in separate objects. Of course you cant have more than one visible sticky state per view, but the last one visited will be the one visible, all the other could be stored indefinitely until explicitly deleted.
This will allow infinite sticky states storage without the need for a dedicated dom element.

**Comment by christopherthielen** [comment]
@Bolza yeah, unfortunately sticky states works by *retaining the dom*, thus you must have a named ui-view for each sticky state. What you describe would undoubtably be awesome, but is something other than sticky states.
