### ISSUE TITLE
Need a tag for 0.0.12-pre1(for Bower)

### ISSUE THREAD

**Issue by impatient** [christopherthielen/ui-router-extras#133]
We're being hit by the bug fixed here:

https://github.com/christopherthielen/ui-router-extras/commit/5aba1345152f589d6cf913d26b5b00c6ee0f1884

It looks like Bower won't resolve the 0.0.12-pre1 version without a tag.

Thanks for the all the work on this.  It saved us a significant amount of time.

**Comment by astyfx** [comment]
+1

**Comment by impatient** [comment]
I forked it and ran the build.

From my bower file:
 "ui-router-extras": "https://github.com/impatient/ui-router-extras.git#7ca4f9f283fab8d097aef5f1e02318e7dfe21efa"

I would obviously prefer to use the main repo.  I'm assuming this ticket will get bumped when a new release is made.

**Comment by impatient** [comment]
Thanks!
