### ISSUE TITLE
Reload sticky state

### ISSUE THREAD

**Issue by Pirfox** [christopherthielen/ui-router-extras#139]
It's mostly a duplicate of #114. I need to reload sticky state when i explicitly come back on the state.
I tried the suggestions on the thread but there was an error.

http://plnkr.co/edit/oFNx453pxMxqnXkDoDJo to see it. Dashboard > list > detail and all link with a sticky state:true and reload:true will throw an error.

Digging through the resolveState i found out that the "reactivate_phase1" is not enterely populated :
```javascript
function stateReactivatedSurrogatePhase1(state) {
    var surrogate = angular.extend(new SurrogateState("reactivate_phase1"), { locals: state.locals });
    surrogate.self = angular.extend({}, state.self);
    return surrogate;
 }
```

Adding the state in the extend seems to solve the problem but not having enough knowledge of ui-router and ui-router-extra I prefer to ask you if this is okay?

**Comment by christopherthielen** [comment]
@Pirfox Thanks for the analysis.  I think your suggestion will work OK as a workaround.  

The surrogate phase 1 is intended to simply match to === from in the path calculations, but I did not take ui-router's 'reload' option into account when computing which states should be reactivated.

A workaround that does not involve modifying ui-router-extras is using the $stickyState.reset() function:

```
 controller : function ($scope , details, $state, $stickyState) {
                    // do things
                    $scope.goToDashboard = function(){
                      $stickyState.reset("top.list");
                      $state.go('top.list', {}, {reload:true});
                    }
                }
```

**Comment by calebthebrewer** [comment]
I'm having a similar issue, but getting a different error: `state.params.$$keys is not a function` on my [plunk](http://plnkr.co/edit/JavUnLkUoxFtKkzWnWv6?p=preview). If this is a separate issue I can create a separate ticket, it is also posted on [stackoverflow](http://stackoverflow.com/questions/28102710/angular-routers-resolve-on-a-stick-statehttp://stackoverflow.com/questions/28102710/angular-routers-resolve-on-a-stick-state).

**Comment by Pirfox** [comment]
@christopherthielen I could use that but I'd really prefer to use a `<a ui-sref='top.list' ui-sref-opts="{reload: true}"/>`
I'll use the workaround for now waiting for a fix or if you have any other ideas

**Comment by Pirfox** [comment]
I played a little with the ```$stickyState.reset()``` but it appears that when the state is reseted other inactive state will appear before the transition, it makes a blink effect.

**Comment by christopherthielen** [comment]
@Pirfox  I think this will be fixed in an upcoming commit.  I built a preview and forked your plunk with it (added the preview as `extras.js`)

Can you check my fork of your plunk: http://plnkr.co/edit/phtOHKWLXlRBX2EK0Q2g?p=preview

**Comment by christopherthielen** [comment]
@calebthebrewer i removed `{ reload: true }`  from your plunk and the resolve is running each time you click "View B Route B".  What versions of UI-Router and Extras were you testing with?

**Comment by christopherthielen** [comment]
@calebthebrewer look at #112 I added support for new ParamSet stuff in december and apparently havent tagged a release since then.

**Comment by calebthebrewer** [comment]
@christopherthielen I was using 0.0.11, but building from the latest commit as per your [stackoverflow](http://stackoverflow.com/a/28174722/1294804) answer resolves the issue. Thanks for digging into this for me.

**Comment by Pirfox** [comment]
@christopherthielen works perfectly! Thank you.

**Comment by christopherthielen** [comment]
I've committed a more complete version of this.  It also works on non-sticky states.

`$state.go(toState, params, { reload: true })` will reload (exit/enter) all states between root to the "toState".  Careful, because any sticky states that are children of any reload states will be exited (this is the basic contract of a sticky state).

`$state.go(toState, params, { reload: "nested.state" })` will reload (exit/enter) all states from `nested.state` and below.
