### ISSUE TITLE
$previousState.get() access to locals.globals (state resolve context)

### ISSUE THREAD

**Issue by keithharvey** [christopherthielen/ui-router-extras#141]
Is there any way to get access to the locals.globals of the previous state?

I'm using breadcrumbs, driven from data.displayName templates and would like to $interpolate these templates to create back button text. $previousState.get, like $state.get, does not return locals.globals. I suspect this is a limitation of the underlying library using an acyclic state graph so navigating up the tree from $current seems to be the only way to get access to the resolve context. Do you know of any workarounds for this?

**Comment by christopherthielen** [comment]
Although it's undocumented, ui-router-extras decorates your state objects with a `$$state()` function which returns the internal state representation.

https://github.com/christopherthielen/ui-router-extras/blob/master/src/stickyState.js#L106

**Comment by christopherthielen** [comment]
so, to be more clear, something like this should work:

```
var prev = $previousState.get();
var internalState = prev.state.$$state();
var data = internalState.data;
```
but as I read your comments, i get more and more confused.  why can't you access 'data' directly from $state.get('foo').data?  Why are you mentioning resolve contexts and navigating up the tree?

**Comment by keithharvey** [comment]
I think you hit the nail on the head with the $$state() function.

To answer your questions, my implementation is based on this: https://github.com/michaelbromley/angularUtils/tree/master/src/directives/uiBreadcrumbs

You are right that access to data is not a problem. I am using $interpolate to render some text for a back button and need from the previous state
  1) the data.displayName template  (e.g. '{{ user.firstName }} {{ user.lastName | uppercase }}' and
  2) the locals.globals of the previous state.

Example code using $$state (warning: not battle tested):

Coffeescript
```coffeescript
angular.module("rawr").factory "stateHelper",
  ($interpolate, $state) ->
    svc = {}

    svc.getDisplayName = (state) ->
      displayName = getObjectValue('data.displayName', state)
      if displayName is 'undefined'
        state.name
      else
        if state.locals?
          interpolationContext = state.locals.globals
        else
          internal_state = state.$$state()
          interpolationContext = getFirstParentLocals(internal_state)
        $interpolate(displayName)(interpolationContext)

    getObjectValue = (objectPath, context) ->
      i = undefined
      propertyArray = objectPath.split(".")
      propertyReference = context
      i = 0
      while i < propertyArray.length
        if angular.isDefined(propertyReference[propertyArray[i]])
          propertyReference = propertyReference[propertyArray[i]]
        else          
          # if the specified property was not found, default to the state's name
          return 'undefined'
        i++
      propertyReference

    getFirstParentLocals = (internal_state) ->
      if internal_state.locals?
        internal_state.locals.globals
      else if internal_state.parent?
        getFirstParentLocals(internal_state.parent)
      else
        'undefined'

    svc
```
Javascript (converted)
```javascript
angular.module("rawr").factory("stateHelper", function($interpolate, $state) {
  var getFirstParentLocals, getObjectValue, svc;
  svc = {};
  svc.getDisplayName = function(state) {
    var displayName, internal_state, interpolationContext;
    displayName = getObjectValue('data.displayName', state);
    if (displayName === 'undefined') {
      return state.name;
    } else {
      if (state.locals != null) {
        interpolationContext = state.locals.globals;
      } else {
        internal_state = state.$$state();
        interpolationContext = getFirstParentLocals(internal_state);
      }
      return $interpolate(displayName)(interpolationContext);
    }
  };
  getObjectValue = function(objectPath, context) {
    var i, propertyArray, propertyReference;
    i = void 0;
    propertyArray = objectPath.split(".");
    propertyReference = context;
    i = 0;
    while (i < propertyArray.length) {
      if (angular.isDefined(propertyReference[propertyArray[i]])) {
        propertyReference = propertyReference[propertyArray[i]];
      } else {
        return 'undefined';
      }
      i++;
    }
    return propertyReference;
  };
  getFirstParentLocals = function(internal_state) {
    if (internal_state.locals != null) {
      return internal_state.locals.globals;
    } else if (internal_state.parent != null) {
      return getFirstParentLocals(internal_state.parent);
    } else {
      return 'undefined';
    }
  };
  return svc;
});

```

The reason I mentioned navigating up the tree is because of how he was populating the breadcrumb display name [here](https://github.com/michaelbromley/angularUtils/blob/master/src/directives/uiBreadcrumbs/uiBreadcrumbs.js#L70).

Thank you for the great library!

**Comment by christopherthielen** [comment]
1) check out $parse service
2) Does that code work for you?  When a state is exited, its locals are cleared.   You may have better luck computing the back button text *right before the transition starts*, while the "previous" state is still active.  

```
angular.module("rawr").factory("stateHelper", function($parse, $rootScope, $interpolate, $state) {
  var getFirstParentLocals, getObjectValue, svc;
  svc = {};
  var pending, previous = "";
  getDisplayName = function(state) {
    var displayName, internal_state, interpolationContext;
    displayName = $parse('data.displayName')(state);
    if (displayName === 'undefined') {
      return state.name;
    } else {
      if (state.locals != null) {
        interpolationContext = state.locals.globals;
      } else {
        internal_state = state.$$state();
        interpolationContext = getFirstParentLocals(internal_state);
      }
      return $interpolate(displayName)(interpolationContext);
    }
  };
  getFirstParentLocals = function(internal_state) {
    if (internal_state.locals != null) {
      return internal_state.locals.globals;
    } else if (internal_state.parent != null) {
      return getFirstParentLocals(internal_state.parent);
    } else {
      return 'undefined';
    }
  };
  $rootScope.$on('$stateChangeStart', function(toState, toParams, fromState) {
    pending = getDisplayName(fromState);
  })
  $rootScope.$on('$stateChangeSuccess', function() {
    previous = pending;
    pending = undefined;
  })
  
  svc.getLast = function() { return previous; }
  return svc;
});
```

**Comment by keithharvey** [comment]
1) Much better, thanks for the tip
2) It did, unfortunately, but only because of common ancestry in my test case. Too early. I think your approach with the change listeners works but would involve doing a wrapper on top of $previousState for memos. Not terrible but perhaps being able to pass along arbitrary data (like my display name) with a memo might be a decent feature for a PR?

**Comment by keithharvey** [comment]
Working plunker: http://plnkr.co/edit/xj8IWd3G2mW9bOZNGLLo?p=preview

**Comment by christopherthielen** [comment]
cool.

**Comment by keithharvey** [comment]
The above implementation has an issue when trying to get previous state name from a controller, since state change success doesn't fire until after that.

A more optimistic resolution seems to fix this:

```javascript
var last_previous = previous = null;

$rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams) {
  last_previous = previous;
  previous = stateHelper.getDisplayName(fromState);
});

$rootScope.$on('$stateChangeError', function() {
  previous = last_previous;
});
```
