### ISSUE TITLE
Sticky state with params is reloaded

### ISSUE THREAD

**Issue by cvrptn** [christopherthielen/ui-router-extras#143]
My issue is a bit complex, and I have encountered it while working in proprietary code, so the information/code snippets I can post are limited.
I am working on a content management system containing articles, and each article has an id, major version and minor version, so they are given relative URL's that are composed as follows:
/article/{articleId}/{majorVersion}/{minorVersion}/edit
I've got the following state configuration:
```javascript
$stateProvider
  .state('article', {
    abstract: true,
    url: '/article',
    templateUrl: 'views/article-main.html'
  })
.state('article.edit', {
    url: '/{articleId}/{majorVersion}/{minorVersion}/edit',
    sticky: true,
    deepStateRedirect: true,
    views: ...
})
//Some additional states nested underneath article.edit
```
I have a tabbar with a tab for each version (combination of articleId, majorVerison and minorVersion) of an article, so I would like to transition between these tabs, while keeping the state for each article in another tab. However, because the sticky states only differ in the values of their parameters, getStickyTransitionType returns {from: false, to: false}, which prevents them from being marked as inactive, and subsequently from being reactivated. Even if I hack getStickyTransitionType to return {from: true, to: true}, they are still marked as "updateParams" states, so they still get reloaded each time.

Am I doing something wrong here? I would really appreciate any advice you can give me on this matter.

**Comment by christopherthielen** [comment]
I've been calling this use case MDI (multiple document interface) and it's not supported.

I wish I had a better answer for you.  Sticky states doesn't support duplicate copies of a given state.   It's technically difficult to implement using UI-Router.  I'm definitely open to discussion on how this could be handled with the existing UI-Router codebase. 

See also #90, #89 and #106

**Comment by pankajkumar** [comment]
+1

**Comment by christopherthielen** [comment]
dupe #74
