### ISSUE TITLE
Resetting $previous state

### ISSUE THREAD

**Issue by keertijoshi** [christopherthielen/ui-router-extras#145]
Is there a way to reset/clear all the previous states without specifying a particular memo name?

**Comment by christopherthielen** [comment]
Nope, but previous states is only 50 loc.  Accepting PRs :)

https://github.com/christopherthielen/ui-router-extras/blob/master/src/previousState.js#L37

**Comment by yppeaxy** [comment]
Hi Christopher,

we need to clear previous state when user logs out but not when user session expires. We use $previousState.get() to know which page to redirect the user to after the log in. This is why we where thinking of an ability to clear the $previousState.
Any advice on what to try here?

thank you!
--y

**Comment by christopherthielen** [comment]
I was fixing bugs in previous state, so I took a couple minutes and made `$previousState.forget()` forget the previous state.

**Comment by yppeaxy** [comment]
Thank you so much!
