### ISSUE TITLE
Modularize code base

### ISSUE THREAD

**Issue by christopherthielen** [christopherthielen/ui-router-extras#146]
Some people only want sticky states, some want DSR, some want future states.

**Comment by christopherthielen** [comment]
summon @amcdnl

**Comment by christopherthielen** [comment]
https://github.com/christopherthielen/ui-router-extras/commit/aebf936db9cd4c7dc8f2b813f20572ba3b07bea6

Now, we have the following modules:
`var moduleNames = [ 'core', 'dsr', 'sticky', 'future', 'previous', 'transition', 'statevis' ];`

Each is built, tested, and minified separately.  The output goes to build/modular directory.   Each module defines an angular module `ct.ui.router.extras.sticky`  for instance.

A special meta-module 'all' includes in each of the individual modules, and defines the "includes everything" angular module `ct.ui.router.extras`.

**Comment by amcdnl** [comment]
:)
