### ISSUE TITLE
$transition not returning promise correctly

### ISSUE THREAD

**Issue by christopherthielen** [christopherthielen/ui-router-extras#152]
from @shanesmith in #150 

Also running into @jvisser's issue so I've created a plunkr below.

http://plnkr.co/edit/po3jqSI7swYrAVaUFwxj?p=preview

Some quick sleuthing tell me that the bug is somehow related to https://github.com/christopherthielen/ui-router-extras/blob/master/src/transition.js#L43 and how it's used a few dozen lines below, probably should be returning data instead...

**Comment by shanesmith** [comment]
Cheers!
