### ISSUE TITLE
Make sticky the parent state in the tabs example.

### ISSUE THREAD

**Issue by leandroz** [christopherthielen/ui-router-extras#160]
Hey @christopherthielen , congrats for the new version!!
I am developing a mobile app using Angular and Cordova right now. I have one state that is like a Facebook feed, but that has three tabs because is split in three different feeds.
Each children state of the feed is a sticky state and now is working perfect.

What i want to do is to make sticky the parent, so when the user goes to other state of the app the entire feed remains loaded when the user returns.

Right now i have a ````ui-view```` in the index.html and then in the feed template i have:
````
ui-view.bg--taupe(name="community@feed" ng-show="currentState == 'feed.community'")
ui-view.bg--taupe(name="friends-dogs@feed" ng-show="currentState == 'feed.friends-dogs'")
ui-view.bg--taupe(name="my-dogs@feed" ng-show="currentState == 'feed.my-dogs'")
````
And the states definition:
````
                .state('feed', {
					url: '/feed',
					templateProvider: ['$templateCache',
						function($templateCache) {
							return $templateCache.get('feed.tpl.jade');
						}
					],
					controller: 'feed.feedCtrl'
				})
				.state('feed.my-dogs', {
					url: '/my-dogs',
					views: {
						'my-dogs@feed': {
							templateProvider: ['$templateCache',
								function($templateCache) {
									return $templateCache.get('my-dogs.tpl.jade');
								}
							],
							controller: 'feed.my-dogs.myDogsCtrl'
						}
					},
					sticky: true,
				})
				.state('feed.friends-dogs', {
					url: '/friends-dogs',
					views: {
						'friends-dogs@feed': {
							templateProvider: ['$templateCache',
								function($templateCache) {
									return $templateCache.get('friends-dogs.tpl.jade');
								}
							],
							controller: 'feed.friends-dogs.friendsDogsCtrl'
						}
					},
					sticky: true,
				})
				.state('feed.community', {
					url: '/community',
					views: {
						'community@feed': {
							templateProvider: ['$templateCache',
								function($templateCache) {
									return $templateCache.get('community.tpl.jade');
								}
							],
							controller: 'feed.community.communityCtrl'
						}
					},
					sticky: true,
				})
				.state('activities', {
					url: '/activities',
					templateProvider: ['$templateCache',
						function($templateCache) {
							return $templateCache.get('activities.tpl.jade');
						}
					],
					controller: 'activities.activitiesCtrl'
				})
````

What is the best way to do these? Adding a new parent state of all of the states, and creating two ui-view, one for matching the feed states and one for the rest of the states of the app?, i only care to keep the feed state loaded.
Thanks!

**Comment by christopherthielen** [comment]
> Adding a new parent state of all of the states, and creating two ui-view, one for matching the feed states and one for the rest of the states of the app?

Yep. Mark `feed` sticky and give it a named `ui-view` and put the rest of your app in a second `ui-view` (un-named, probaby)

**Comment by leandroz** [comment]
Thanks @christopherthielen is working like a charm!

**Comment by leandro-shifteight** [comment]
@christopherthielen I have the parent sticky and the three tabs sticky too. This is because I need the transition between tabs to keep the DOM and then keep the DOM when the user transition to elsewhere in the app. The three tabs are like Facebook feeds and is expensive to reload them.
The problem is that the 3 scopes and watchers are active while the user is in other state, I am emiting events and the scopes that should actually be inactive are working.
This makes the digest slow when we have a lot of posts in the feed. Is there a better way to do it?, maybe with previousState? I can't figure out a better solution.
