### ISSUE TITLE
ui-router-extra not work with angularjs 1.3

### ISSUE THREAD

**Issue by ElenaNesgovorov** [christopherthielen/ui-router-extras#163]

**Comment by ElenaNesgovorov** [comment]
I start to use ui-router and ui-router-extras for your angular application,few week ago we upload new version of angularjs ,After that our application just stop working. Can you please fix the ui-router-extras for version 1.3 of angularjs too? Thanks and best regards

**Comment by Phoscur** [comment]
Kinda wanted to use futureStates with angular 1.3... +1

**Comment by ElenaNesgovorov** [comment]
yes

On Sun, Feb 22, 2015 at 8:23 AM, Phoscur <notifications@github.com> wrote:

> Kinda wanted to use futureStates with angular 1.3... +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christopherthielen/ui-router-extras/issues/163#issuecomment-75422176>
> .
>



-- 
Elena Nesgovorov.:)

**Comment by maciej-gurban** [comment]
It works for me with:
AngularJS: 1.3.13
UI Router: 0.2.13
UI Router Extras: 0.0.13

Have you tried enabling the debugging mode of ui router extras and seeing what exactly fails?

**Comment by goleafs** [comment]
After updating to angular 1.4 rc1 sticky states don't seem to actually stick anymore...

**Comment by christopherthielen** [comment]
ui-router-extras should work fine with angular 1.3 and 1.4

I updated the demo site to:
- angular 1.4.0
- ui-router 0.2.15
- ui-router-extras 0.2.13
- angularAMD 0.2.1

If something is not working, please open a new issue and provide *details*

**Comment by goleafs** [comment]
yep, working again with the latest bits, thanks.
