### ISSUE TITLE
State Unknown

### ISSUE THREAD

**Issue by marcus30** [christopherthielen/ui-router-extras#164]
Here's the use case: I have a tabbed navigation app with a bunch of nested views. Eventually the app tries to route to views connected to other tabs in the application. Instead of jumping tabs and creating an awkward user experience, I'd like to be able to route to the view within the current tab. Obviously, creating a state for each potential scenario would be daunting. So the issue is the full stateName would be unknown until there is an attempt to reroute the app. I've been through the API and source code, but just haven't been able to get it working. I am probably missing something. Ideas?

http://codepen.io/howtofryapixel/pen/bNaqmY

**Comment by christopherthielen** [comment]
Hey, sorry it's taken so long to respond, ui-router-extras has taken a back seat lately.

I'm not really sure what your question is, but from what you've posted, I'm don't think future states are an appropriate way to model your app.  Maybe stock ui-router named views makes more sense?
