### ISSUE TITLE
FYI  Build error

### ISSUE THREAD

**Issue by rickj33** [christopherthielen/ui-router-extras#165]
I just a clone, and tried to do a build but it failed.
I found the reason was due to lodash being installed in a different folder than specified in the files.js and karma.any.conf.js. after i corrected the paths in the two files, everything built fine.

After i did a npm install and bower install, my lodash.js file is located in bower_components/lodash and not in bower_components/dist/lodash

**Comment by maximumduncan** [comment]
This is likely broken because file structure of a bower-sourced lodash changed with lodash v3.0.0.

**Comment by jakedowns** [comment]
+1 thanks for posting this
