### ISSUE TITLE
deepStateRedirect only remember child state

### ISSUE THREAD

**Issue by dylaninvodo** [christopherthielen/ui-router-extras#170]
Here is my issue:
* User browses to state with parameter: **parent.param1**
* User browses to child modal state with deepStateRedirect enabled: **parent.param1.modal**
  * default redirect immediately triggers child state: **parent.param1.modal.sub1**
* User closes modal (back to parameterized parent): **parent.param1**
* User browses to different parameter for parent state: **parent.param2**
* User opens modal again: **parent.param2.modal**
  * deepStateRedirects to last seen full state of **parent.param1.modal.sub1**

I'd rather the deepStateRedirect only redirected the part of the state tree that is a child of modal1 so that my parent.param* is not updated when the modal opens. Is this possible?

**Comment by christopherthielen** [comment]
I think you want to specify `params: true` on your DSR state `parent.modal`.

The docs imply that the parameters are only accounted for on the DSR state, but in truth, they are accounted for on the transition itself.

http://christopherthielen.github.io/ui-router-extras/#/dsr
