### ISSUE TITLE
relative ui-sref with sticky states

### ISSUE THREAD

**Issue by oste** [christopherthielen/ui-router-extras#172]
Are relative transitions supported when using sticky states? 

```ui-sref=".({page: 2})"``` gives me "Error: Cannot transition to abstract state '.'"

The error starts here https://github.com/christopherthielen/ui-router-extras/blob/master/src/sticky.js#L455 And then is thrown in UI-router at this code

```if (toState[abstractKey]) throw new Error("Cannot transition to abstract state '" + to + "'");```

**Comment by christopherthielen** [comment]
yes.

**Comment by oste** [comment]
@christopherthielen  so that is the correct syntax?

**Comment by christopherthielen** [comment]
yes

**Comment by oste** [comment]
@christopherthielen here is a simple plunk that shows the error when clicking the button http://plnkr.co/edit/1HlrRFPrN2HWAVxfNIQS?p=preview 

Looking forward to seeing what you can find! Thanks

**Comment by christopherthielen** [comment]
http://plnkr.co/edit/csYIQfe12XZ42zRle60L?p=preview

ui-sref relative links are relative to the state they're written out in.  Your example is putting a ui-sref in the root state, so "." is the root state.

**Comment by oste** [comment]
ok that explains it, it doesn't make sense for me to put these links inside the state template so maybe I will end up with an ```ng-click``` event that uses the current state
