### ISSUE TITLE
$previousState and states without URL

### ISSUE THREAD

**Issue by tomasszabo** [christopherthielen/ui-router-extras#175]
I've a problem with `$previousState` service. It's not remembering the previous state. I was able to track down the problem to:

    var fromState = from.state && from.state.$$state && from.state.$$state();
    if (fromState && fromState.navigable) {
        lastPrevious = previous;
        previous = $transition$.from;
    }

The thing is, that my states doesn't have `url` defined (therefore `navigable` is missing), only the first one has `url` defined (and therefore it is then resolved as the only one previous state in the whole app). 

Sorry, I don't have an idea how to fix it right now, but at least I wanted to let you know. Anyway, thank you for a great extension!

**Comment by demisx** [comment]
+1
