### ISSUE TITLE
Using Sticky State for multiple tabs/category

### ISSUE THREAD

**Issue by dzuncoi** [christopherthielen/ui-router-extras#177]
Would it be possible to use sticky state for multiple tabs ?
Let's assume we have 50 tabs in our website, so do we need to create 50 states for each tabs? Is there any easier way to combine those state, and is it a good approach for this situation?

**Comment by christopherthielen** [comment]
Yes, you need one state and one named ui-view for each sticky state.  Quite a few people have been asking about having the same state open multiple times.  This is not supported, and I do not think it can be easily achieved.  However, if each of the 50 tabs are for different states in your app, then yes you can have 50 sticky states... you must have one named ui-view for each sticky state.
