### ISSUE TITLE
$futureStateProvider addResolve api

### ISSUE THREAD

**Issue by kbdaitch** [christopherthielen/ui-router-extras#178]
@christopherthielen I have been using this API for a long time in production. A question has come up for me when trying to integrate in a new project using `systemjs`.

I would think that according to docs, it should hold off on routing no matter what but my experience today is that `$futureStateProvider.addResolve` can only delay routing if the state to transition to is not already defined.

If the target state is already defined, my promise is resolving way after the successful state transition. Is this to be expected?

In my case, I principally want `Startup.awake` to hold routing, but I am being forced to take the `coreStates` out of the `angular.module` call, and use it lazily too:
```js
           // By deliberately holding off state definition, hold off routing
            return System.import('js/core/states/app').then(function(m) {
                return $ocLazyLoad.load(m.coreStates)
            }).then(function() {
                return Startup.awake();
            })
```

Thoughts?

**Comment by christopherthielen** [comment]
I think `$futureStateProvider.addResolve` should only delay routing to states that don't exist ($stateNotFound handler).  

Have you looked into `$urlRouterProvider.deferIntercept()` / `$urlRouter.listen()`?  I think that API should help you defer routing globally.

**Comment by kbdaitch** [comment]
Got it. Thanks @christopherthielen. That works.
