### ISSUE TITLE
License file is missing from repo

### ISSUE THREAD

**Issue by HipsterZipster** [christopherthielen/ui-router-extras#180]
Hi,
Can you please add a license file? Many firms require any open-source packages to have a license file in order for it to be used in their software. Which license is this project under? MIT?

**Comment by fdn** [comment]
+1, would like to use this but cannot since there is no licensing attached.

**Comment by HipsterZipster** [comment]
At the minimum, can someone please answer which license this project is using? MIT? Apache? If you tell me, I'll create the PR for the license.

**Comment by ScottWeinstein** [comment]
+1
