### ISSUE TITLE
Sticky state DOM tree not being destroyed when leaving parent

### ISSUE THREAD

**Issue by antch** [christopherthielen/ui-router-extras#185]
I have my states laid out like so:

    - flow1
    - flow2 (sticky, named view)
        - flow2.substate

When I navigate from `flow1` to `flow2.substate` and then go back to `flow1` the DOM for `flow2` is not being destroyed.  Given the following from the Sticky State documentation, this seems incorrect:

<blockquote>
The DOM and $scope of a Sticky State (and all activated substates) is retained until the parent state of the sticky state is exited.
</blockquote>

I created an example demonstrating this behavior: http://plnkr.co/edit/QIW3MNItJNtJPwwjgCFD?p=preview

I'm not sure if I have a fundamental misunderstanding, or if there is a legitimate issue.

**Comment by christopherthielen** [comment]
Hi, the parent state of your sticky state is the unnamed root state (`""`), which is never exited.  That behavior is what I would expect out of sticky states.  cheers! :beer:
