### ISSUE TITLE
What is the current state and the future of this project

### ISSUE THREAD

**Issue by adriatic** [christopherthielen/ui-router-extras#190]
As I just discovered it I am very impressed and surprised that ui-router-extras is not a lot more visible and used everywhere. Is this just the "marketing problem"? **Why is this not a regular part of the ui-router** is the next obvious question.

Rather than looking through the whole history of open and closed issues, can I impose on the author and existing users to give me their answer to my questions?

I am certainly going to make this a prominent part of my app.

**Comment by christopherthielen** [comment]
FYI, I'm also a ui-router project maintainer.  

Some features of extras will be going in main ui-router after the bump to ui-router 1.0.  Other features are questionable for inclusion, or will definitely not be included.  

The main features of ui-router-extras are :

| feature | notes
-------------------------
| transition promise | A much improved version is now in 1.0 codebase |
| deep state redirect | Will be mostly obsoleted by a 15 line recipe using the new transition API | 
| sticky | Will probably remain as a third party addon |
| future | post-1.0 timeline, I'd like future states (or something close) in main UI-Router |
| previous | This API is mediocre at best, and I think we can do better |
| statevis | remain as a third party addon |


We're making good progress on ui-router 1.0, and I hope you can see a preview release in the coming weeks (although I've made that claim before and it didn't exactly turn out how I predicted)
