### ISSUE TITLE
stateFactory support for annotation

### ISSUE THREAD

**Issue by atgillette** [christopherthielen/ui-router-extras#192]
Hi,

I'm using your library in combination with webpack and oclazyload on a prototype project and the whole thing works well together.  I'm able to break a large monolithic application into sub-applications.  The only problem that I'm encountering is the use of $futureStateProvider.stateFactory on my module.config:

```javascript
var ocLazyLoadStateFactory = function ($q, $ocLazyLoad, futureState) {
    var deferred = $q.defer();
    $ocLazyLoad.load(futureState.module).then(function(name) {
        deferred.resolve();
    }, function() {
        deferred.reject();
    });
    return deferred.promise;
};

$futureStateProvider.stateFactory('ocLazyLoad', ocLazyLoadStateFactory);
```

When I attempt to uglify the code, it breaks because how uglify replaces variable names.  I was wondering if you can add support for angular-style annotations, as this practice is becoming commonplace.

Thanks,

Adrian

**Comment by christopherthielen** [comment]
I'm invoking the state factory using injector.invoke, so it should support annotations already.

```
ocLazyLoadStateFactory.$inject = ['$q', '$ocLazyLoad', 'futureState'];
function ocLazyLoadStateFactory($q, $ocLazyLoad, futureState) {

};
```
-or-
```
var ocLazyLoadStateFactory = ['$q', '$ocLazyLoad', 'futureState',
function ($q, $ocLazyLoad, futureState) {

}];
```

Re-open if I'm wrong

**Comment by christopherthielen** [comment]
https://github.com/christopherthielen/ui-router-extras/blob/0.0.13/src/future.js#L131-L135
