### ISSUE TITLE
remove existing state before going to previous

### ISSUE THREAD

**Issue by jmls** [christopherthielen/ui-router-extras#195]
so, I was trying to implement the following workflow

a->b->c->b

when in c, the user presses save or cancel, then they are moved back to b

this works by $previousState.go()

the "problem" is that c is now part of the history, so if the user press the "back" button on the brower then they are taken back from b to c then b then a

can I pop / remove the c state so that it can't be in the "back" list ?

**Comment by shaungrady** [comment]
You can achieve this by passing an `options` object to the `go` method. E.g.:
``` javascript
$previousState.go('', {
  location: 'replace'
});
```

`$previousState.go` is a wrapper for `$state.go`, so the options work the same way. Docs for the `go` method's `options` argument are here: https://github.com/angular-ui/ui-router/wiki/Quick-Reference#options

**Comment by jmls** [comment]
that worked, thanks
