### ISSUE TITLE
only delete futurestate if successfully lazy loaded ... otherwise leave futurestate in place

### ISSUE THREAD

**Issue by spkarjalainen** [christopherthielen/ui-router-extras#196]
Hi Christopher,

Would it be possible to change the futurestates module so that when lazy loading of a future state is rejected (i.e. user is not presently authorised to access the underlying state files), it can leave the futurestate in place so that if a user consequently signs in or receives upgrades privileges, the future state is still available and can successfully be lazy loaded at that time (even though it failed at an earlier time)?
I noticed in your source that you delete the futurestate regardless of the lazy load outcome.

Thanks
Sam

**Comment by christopherthielen** [comment]
I think that's reasonable as a configurable option.
