### ISSUE TITLE
Help configuring tabs use case using angular.ui

### ISSUE THREAD

**Issue by JobaDiniz** [christopherthielen/ui-router-extras#199]
I know I know... another question about this... I saw a few already here. Even after reading the docs, I couldn't get it right for my use case.

I have 2 tabs (Account and Survey). When users go to `/account` I want the *Account* tab to be activated. When users go to `/account/survey` I want the *Survey* tab to be activated.

Do I have to define 3 states for this? *- I wish I could just define 2*

**Config**
```
 $stateProvider.state('main.account', {
                url: '/account',
                templateUrl: 'account/page/templates/account-page.html',
            });

            $stateProvider.state('main.account.main', {
                url: '/',
                views: {
                    'account': {
                        template: '<ng-include src="' + "'account/page/templates/account-membership.html'" + '></ng-include>',
                        controller: 'AccountPageController'
                    }
                },
                sticky: true
            });
            $stateProvider.state('main.account.survey', {
                url: '/survey',
                views: {
                    'survey': {
                        templateUrl: 'account/page/templates/survey-tab.html'
                    }
                },
                sticky: true
            });
            $stickyStateProvider.enableDebug(true);
```
**account/page/templates/account-page.html**
```
<div class="container my-account">
    <div class="row with-paddings">
        <tabset type="pills" class="my-account-menu">
            <tab heading="My Account" ui-sref="main.account.main">
                <div ui-view="account"></div>
            </tab>
            <tab heading="My Tennis Experience" ui-sref="main.account.survey">
                <div ui-view="survey"></div>
            </tab>
        </tabset>

        <it-error-message ng-show="error"></it-error-message>
    </div>
</div>
```

The problem is that when user goes to `/account` nothing is shown; that's because the `main.account.main`state is not activated; I have to manually do this:
```
$rootScope.$on('$stateChangeSuccess', function (event, toState) {
                if (toState.name === 'main.account')
                    $state.go('main.account.main');
            });
```

Is there a way to configure only 2 states for this? I don't want `main.account.main` state. Only `main.account` and `main.account.survey` is enough.

**Comment by christopherthielen** [comment]
I've created a minimal sticky state example with the following features:
- Two Tabs (contents shown/hidden using ng-show)
  - Account Tab
    - Has 2 substates, `stuff` and `things`
    - Reactivates the last known substate (stuff or things) when clicked (using Deep State Redirect)
  - Survey Tab has no substates
- The Active Tab is highlighted (using ui-sref-active)
- StateVis directive shows you the active and inactive states

http://plnkr.co/edit/bFMLqLENmPFfCD0XCz8V?p=info

**Comment by JobaDiniz** [comment]
Hi @christopherthielen, thanks, but your sample doesn't work. Plunker couldn't find the templates (account & survey).

Nevertheless, what you did is what I've currently done.

> Do I have to define 3 states for this? *- I wish I could just define 2*

You defined 3 states: `tabs`, `tabs.account` and `tabs.survey`. I wish I could define only `tabs` and `tabs.survey`. But it is not that a big deal to define 3.. I'm okay with that.
What I'm not okay with is having to write (using your example):
```
$rootScope.$on('$stateChangeSuccess', function (event, toState) {
                if (toState.name === 'tabs')
                    $state.go('tabs.account');
            });
```
When I run your sample, neither `tabs.account` or `tabs.survey` is activated. I need to manually write the above code.

I tried to set `abstract`, to no avail:
```
$stateProvider.state('tabs', {
      abstract: true,
      url: '/',
      templateUrl: 'tab-viewport.html',
  });
```

In the *tab scenario*, I think one tab must be activated by default.

**Comment by christopherthielen** [comment]
> but your sample doesn't work. Plunker couldn't find the templates (account & survey).

Plnkr seems to sometimes have difficulties with fetching resources.  Try refreshing it.  Works fine here in multiple browsers.

> In the tab scenario, I think one tab must be activated by default. 

[Yea? Well... you know, that just, like uh... your opinion, man.](https://www.youtube.com/watch?v=pWdd6_ZxX8c)

> I tried to set abstract, to no avail:

Where'd you get that idea?  Abstract simply means the state cannot be navigated to directly.  From the docs:

> An abstract state will never be directly activated, but can provide inherited properties to its common children states.

If you want that behavior (default substate), configure it using deep state redirect.

```
  $stateProvider.state('tabs', {
    url: '/',
    templateUrl: 'tab-viewport.html',
    dsr: { default: 'tabs.account' }
  });
```

**Comment by JobaDiniz** [comment]
> dsr: { default: 'tabs.account' }

Didn't know about that, thanks!

My [answer](http://tclhost.com/R0DiSqZ.gif) to your video.

**Comment by christopherthielen** [comment]
cheers
