### ISSUE TITLE
changing to a sticky state

### ISSUE THREAD

**Issue by jmls** [christopherthielen/ui-router-extras#201]
Is it possible to change an existing state like this

```javascript
{
  name: 'myState',
  state:{
              url: '/myState',
              controller: 'listController',
              controllerAs: 'controller',
              templateUrl: '/dyn/myState/list.html'
          }

}
```
to a "sticky" state once it has already been loaded into $stateProvider ? (ie change the existing record)

or should I remove the state, and create a new one ? If so - is all I need to do is add 
"sticky: true" 
or is there more to do ?

sorry, very noob questions here, but trying to wrap my head around this ;)

thanks

**Comment by christopherthielen** [comment]
I don't think you can make a state sticky after it has been registered.  Also, you need to use a named ui-view for the sticky state, per the docs.
