### ISSUE TITLE
2 tabs open with different navbars

### ISSUE THREAD

**Issue by PieterJanVdb** [christopherthielen/ui-router-extras#203]
Is it possible to have 2 tabs open on different navbars? By this I mean the following:

http://i.imgur.com/DF6FASE.jpg

I'd for example like to have a tab from the top nav open and one from the bottom nav. I'm not quite sure if it's possible with ui-router states.

Thanks in advance.

**Comment by christopherthielen** [comment]
are those supposed to be nested tab-bars? i.e., the top tabs/navbar, does that drive the contents of the bottom tabs/navbar?  If so that's standard UI-Router stuff.  Are they supposed to operate indepedently? If so, that could be two sticky states, each with their own tabs/navbar.
