### ISSUE TITLE
simple sticky state example

### ISSUE THREAD

**Issue by jmls** [christopherthielen/ui-router-extras#204]
so, I've been fighting this for three days now and realise that my javascript-foo is leaving an awful lot to be desired. 

My goal is simple : I am in a page where the user clicks on a button : this button does a $state.go("DesiredState") 

However, this DesiredState is to be shown as a dialog / popup whatever over the top of the current page, and when the user closes / dismisses the dialog, that page is to retain it's state

Simple, right ?

Can someone please show me the bare minimum required to get this functionality working ? From the ui-view , to the definition of the views of state etc. 

It's all far too confusing for a noob :(

appreciate any help. thanks.

**Comment by christopherthielen** [comment]
I created this plunk which is much simpler than the full modal demo
http://plnkr.co/edit/qgt0RkEnXDPDTdMJPIfy?p=info
