### ISSUE TITLE
Support preemptive sticky states

### ISSUE THREAD

**Issue by Grety** [christopherthielen/ui-router-extras#209]
Although current spec says each sticky state should reside in a unique named view, i don't see reasons to not allow sticky states be preemptive and force each other out of same view.

Scenario is for supporting a modal over states that are not allowed to co-exist. Let's say we have _state1_ and _state2_ whose views and controllers should not exist at the same moment. And there is a _modal_ state which can be transitioned from _state1_ or _state2_. We can mark _state1_ and _state2_ as sticky and this will solve transitions between _modal_ and one of _state1_ and _state2_. However, if we switch from _state1_ to _state2_ the first one should should exit. This doesn't happen because it's sticky. So we should have a way to forcefully exit a sticky state. One way is to have an explicit method, another one is to allow sticky states force each other out of its view and the new state should remain sticky.

This [fiddle](http://jsfiddle.net/Grety/4d1fcfth/) demonstrates the issue with angular@1.3.10, ui-router@0.2.13 and ui-router-extras@0.0.14

**Comment by oste** [comment]
+1 I was not able to successfully update to 0.0.14 because my configuration includes two sticky states that point to the same ui-view. I have a modal that can be opened from either sticky state. See configuration:

```
        .state('home', {
            url: "/",
            sticky: true,
            views: {
                main: {
                    templateUrl: "main.html",
                    controller: 'MainCtrl'
                }
            }
        })
        .state('another', {
            url: "/another",
            sticky: true,
            views: {
                main: {
                    templateUrl: "another.html",
                    controller: 'AnotherCtrl'
                }
            }
        })
        .state('modal', {
            url: "/modal",
            controller: 'ModalCtrl'
           onEnter: ...
```

After updating to 0.0.14 the first sticky that the user visits is being used each time the modal opens regardless of the most recent sticky state.

**Comment by Grety** [comment]
Version 0.0.14 however fixed an issue with switching between sub-state of a sticky and a sub-state of a non-sticky

**Comment by Grety** [comment]
While I was fixing this I found a method that is not mentioned in docs yet, It can be a workaround for those who miss this functionality until author accepts the pull request (if accepts at all). `$stickyState.reset(stateName, [stateParams])` explicitly forces a state to exit

**Comment by Grety** [comment]
Enthusiasts are welcome to test via `bower install grety-ui-router-extras#0.0.15-alpha`

**Comment by christopherthielen** [comment]
There's less corner case magic if you just organize the states like this:

```
 .state("stuck", { 
   sticky: true,
   views: {
     main { template: '<div ui-view></div>' } 
  })
 .state('home', {
            url: "/",
            templateUrl: "main.html",
            controller: 'MainCtrl',
            parent: "stuck"
        })
        .state('another', {
            url: "/another",
            templateUrl: "another.html",
            controller: 'AnotherCtrl',
            parent: "stuck"
        })
        .state('modal', {
            url: "/modal",
            controller: 'ModalCtrl'
           onEnter: ...
```

**Comment by Grety** [comment]
This doesn't work as sticky for `another` or `home` when 'modal' has a template, it wasn't mentioned that 'modal'  state is rendered using `$modal`...
Anyway current behavior IS a bug. First the state behaves as sticky, then after switching it doesn't. Even after returning to original state. And there is not error reported...

**Comment by christopherthielen** [comment]
> Anyway current behavior IS a bug.

I disagree. The docs mention that each sticky state must have its own named ui-view.

**Comment by christopherthielen** [comment]
@Grety 
I updated your fiddle with the code changes I mentioned... it works fine.  Can you update it with your $modal service? I suspect it works fine.

https://jsfiddle.net/bx4L3xus/4/

**Comment by Grety** [comment]
@christopherthielen Yes indeed it works! Thanks. I must have missed the point that `modal` is not a child of `stuck`

**Comment by Grety** [comment]
Anyway, erroneous behavior should be reported even if you assume that preemptive states are not required
