### ISSUE TITLE
Multiple views sticky state

### ISSUE THREAD

**Issue by gilsmdt** [christopherthielen/ui-router-extras#213]
Hi,

I've have this setup
1. Primary view (sticky + DSR)
2. Secondary view (sticky + DSR)
2.1 nested view

1. getting into state A in primary view
2. getting into state B in primary view
3. getting into state C.C1 in secondary view
4. getting into state C.C2 in secondary view

for some reason when changing to state C2 in secondary view the state in Primary view is changed.
Is this a bug or it's not supported to have sticky views in multiple views?

**Comment by gilsmdt** [comment]
Hi,

I've checked it with version 0.13 and it works fine.
Something changed on 0.14 that causes this issue.

**Comment by juliansniff** [comment]
Adding my plunker with the same problem.  Version 0.13 does not have this issue.

http://plnkr.co/edit/6ZQscNVqlNhzaqCwRyrp?p=preview

**Comment by winniehell** [comment]
I made a similar example before finding this issue.

Select `Bacon`, `Jellyfish`, `Garlic`, `Spam`, `Octocat` in that order and you'll end up with `I like Bacon with Octocat!` though `Spam` is selected.

0.0.14 does not work: http://plnkr.co/edit/8GLYjQ?p=preview
0.0.13 works: http://plnkr.co/edit/FKCRwK?p=preview

**Comment by christopherthielen** [comment]
@winniehell both plunks behave the same for me, unless I'm misunderstanding something.

**Comment by winniehell** [comment]
Strange, this is how it looks for me in Firefox:

# 0.0.13
![0 0 13](https://cloud.githubusercontent.com/assets/1652293/8668593/f68387fe-2a0c-11e5-9c9c-08b13bd50b79.png)

# 0.0.14
![0 0 14](https://cloud.githubusercontent.com/assets/1652293/8668596/ff54b6d2-2a0c-11e5-823b-429a33ee7c87.png)

**Comment by winniehell** [comment]
It is important to have the exact same order as I have written it above for the bug to appear. This works for example:

* `Bacon`
* `Garlic`
* `Spam`
* `Jellyfish`
* `Octocat`

**Comment by vellotis** [comment]
I ran into the same bug. Before I found this issue report I made this [plunker](http://plnkr.co/edit/FCCAFroln0d0WyCgAIMY?p=preview).

v0.0.13 works without issues for my plunker.

**Comment by asoesilo** [comment]
+1

**Comment by christopherthielen** [comment]
dupe #212

**Comment by christopherthielen** [comment]
@winniehell I believe I have a fix for #217 which fixes your plunker:

http://plnkr.co/edit/uu5EQFUEcKrwKnuuqrZv?p=preview

Also, it's interesting to note that I can't get your plunker to fail using Chrome.  Using Firefox, it fails just like you describe.

**Comment by christopherthielen** [comment]
@vellotis your plunker is fixed by removing the "sticky: true" on the `.one` and `.two` substates.  Sticky states *must* have a unique named ui-view to plug into.  If you need one/two to be sticky as well, create named ui-views for them.

http://plnkr.co/edit/55eg8Ln5bp3YDswWgThu?p=preview

**Comment by christopherthielen** [comment]
@juliansniff With a little tweak, your plunker is solved with the fix for #217 

Multiple sticky states cannot "share" a named view (in your plunk, they're both trying to use 'main' named view).  I pulled the sticky state up to a parent state, then made home and about as children to the parent sticky state.

http://plnkr.co/edit/3aYRAwsZ53RAXtA1VXeE?p=preview

**Comment by vellotis** [comment]
I played around with your improved plunker. It still misbehaves. Modified the order of these links: http://plnkr.co/edit/rxsFx0WPxbbu4Yz0WSfD?p=preview

**Comment by christopherthielen** [comment]
@vellotis sorry, I needed to plug in the new 0.0.15-pre1 with the fix for #217 for your plunk as well

http://plnkr.co/edit/Lvud4PKb27T2qYURVKCK?p=preview

**Comment by christopherthielen** [comment]
@vellotis ping, can you confirm please?  
Everyone else can you read my comments? I think this issue is ready to be closed.

**Comment by vellotis** [comment]
@christopherthielen Sry. I confirm that it is working and you can close the issue.

**Comment by gilsmdt** [comment]
Looks good on the plnkr.
I'll test it after the weekend on our code and verify.

Thanks for handling it.

**Comment by christopherthielen** [comment]
Closing as fixed.
