### ISSUE TITLE
Omnipresent modals and loading sticky state on page refresh. 

### ISSUE THREAD

**Issue by lstone** [christopherthielen/ui-router-extras#219]
I use sticky states to deactivate the application and then load an omnipresent modal anywhere I want. This works great except when I open the modal and refresh the browser page. Doing this makes the modal load correctly, but the "sticky" state behind it is not loaded because the app loses that state information via the page refresh. Is there a way to load a deactivated sticky state behind a modal?

**Comment by lstone** [comment]
Answering my own question here with a little hackery

```coffeescript  
  # on page refreshes no previous sticky state will exist and nothing will load behind the modal.
  # in this case determine the state of the feedItem and set the background modal state to the
  # correct state
  setup: (feedItem) ->
    if $stickyState.getInactiveStates().length is 0
      # load the background state
      @defaultBackgroundState = 'app.myDefaultState'
      $state.go(@defaultBackgroundState, $stateParams, { location: false })
```

**Comment by kasperlewau** [comment]
I would attach a listener to the `$window.beforeunload` event, store away a reference to the sticky state temporarily in some storage solution and fetch it back out when the page reloads. 

When the page reloads, we check for the existence of such an entity in the storage solution of choice, go to *that* state first and then pop open the modal (if the modal was open at the time of `unload`, of course). At least that's how we at my company solved the problem of 'modal everywhere - but which state was it in the background again?'.

So I guess it's *sort* of what you are doing but the `app.myDefaultState` looks to me like a generic/static fallback solution as opposed to a dynamic background state? 

I don't think there's anything built into ui-router-extras to handle the case you present, not to my knowledge at least.

**Comment by christopherthielen** [comment]
>     if $stickyState.getInactiveStates().length is 0
Hey, that's clever!

I wonder how does your modal remain active though, since you supersede the initial transition with `$state.go(@defaultBackgroundState, $stateParams, { location: false })`

I would think something like `$state.go(@defaultBackgroundState, $stateParams, { location: false }).then(() -> $state.go(thisState, $stateParams))` would be necessary

**Comment by christopherthielen** [comment]
Added an example to the Sticky Modal demo.
