### ISSUE TITLE
TypeError: Cannot read property '$$hashKey' of undefined

### ISSUE THREAD

**Issue by robertgartman** [christopherthielen/ui-router-extras#221]
When using _Previous States_ in combination with [angular-permission](https://github.com/Narzerus/angular-permission) I triggered an exception that required quite some debugging to figure out the root cause of. I'll share it here to spare your time if you're in the same situation. Perhaps there is also a way to make UI-Router Extras more robust (or forgiving).

**Background**
UI-Router-Extras decorate UI Router's _$state.transitionTo_
```javascript
// Decorate $state.transitionTo.
$state.transitionTo = function (to, toParams, options) {
```
This part keeps a track of UI Router transitions. That data is then used when UI-Router-Extras catch UI Router's _$stateChangeStart_
```javascript
$rootScope.$on("$stateChangeStart", function (evt, toState, toParams, fromState, fromParams) {
    var depth = transitionDepth;
```

So far, all in order.

**Issue**
Problems appear when you introduce angular-permission, which supports RBAC based on UI Router states.
But... angular-permission is also capturing the _$stateChangeStart_ event and it has logic that prevents further propagation of as well as (re)transmitting the  _$stateChangeStart_ event.
Result of this is that UI-Router-Extras can get "out of sync" with the states and you end up with:
```
2015-07-21T20:03:43.960+0200  TypeError: Cannot read property '$$hashKey' of undefined
    at baseExtend (https://localhost:4443/bower_components/angular/angular.js:413:14)
    at Object.extend (https://localhost:4443/bower_components/angular/angular.js:455:10)
    at https://localhost:4443/bower_components/ui-router-extras/release/ct-ui-router-extras.js:1689:35
    at Scope.$get.Scope.$broadcast (https://localhost:4443/bower_components/angular/angular.js:16149:28)
    at https://localhost:4443/bower_components/angular-permission/dist/angular-permission.js:58:29
    at processQueue (https://localhost:4443/bower_components/angular/angular.js:14551:28)
    at https://localhost:4443/bower_components/angular/angular.js:14567:27
    at Scope.$get.Scope.$eval (https://localhost:4443/bower_components/angular/angular.js:15830:28)
    at Scope.$get.Scope.$digest (https://localhost:4443/bower_components/angular/angular.js:15641:31)
    at Scope.$get.Scope.$apply (https://localhost:4443/bower_components/angular/angular.js:15935:24)
```

The exception above is triggered when the same _$stateChangeStart_ event hits UI-Router-Extras' _$stateChangeStart_-event listener twice. My theory of the root cause:
1. UI Router broadcast a $stateChangeStart
2. UI-Router-Extras capture the $stateChangeStart event. All fine.
3. angular permission capture the $stateChangeStart event, blocks propagation and then does a retransmit (i.e. broadcast)
4. UI-Router-Extras capture the $stateChangeStart event again. Code breaks.

Versions:
* angular-ui-router: 0.2.15
* angular-permission: 0.3.1
* ui-router-extras: 0.0.14

**Comment by platdesign** [comment]
ran into the same issue... is there any workaround?

**Comment by robertgartman** [comment]
None that I’m aware of. I looked briefly into the possibility of controlling the order of event processing. If ui-router-extra would be ahead of angular permission when processing the events I think everything should work. I pretty soon took another route and I have now removed "previous states" from my code.

**Comment by goodies4uall** [comment]
I had the same problem and after implementing platdesign's fix I have not seen that error anymore.

**Comment by christopherthielen** [comment]
tentatively assigning 0.0.15 milestone

**Comment by christopherthielen** [comment]
I looked at the angular-permission source code.  I don't think the `$transition$` promise (and therefore also previous state) will be compatible with angular-permission.  

The guard code in PR #230 isn't going to work because it corrupts the transition data stack (things won't get cleaned up properly).  I'm going to add a short circuit to that function.  It will render previous state mostly broken for transitions which angular-permission modifies, but shouldn't blow up.

I'll commit that "short circuit" code in a bit and build a 0.0.15-pre3 which I'd like you to try @goodies4uall @platdesign

**Comment by christopherthielen** [comment]
This should be "fixed" (I added the guard code to at least stop the $$hashKey error from showing up).  

Please try the `0.1.0-pre5` build found here: https://rawgit.com/christopherthielen/9c8775888f1650b7934d/raw/1c62623b591ec4dea80ba7674a8509e73cc83a64/ct-ui-router-extras.js

**Comment by IliaSyrtsou** [comment]
Issue is still reproducible.
Whenever I try to transition to state protected by a permission, the $$hashKey exception is always raised.
Versions:

angular-ui-router: 0.2.15
angular-permission: 0.3.1
ui-router-extras: 0.1.0-pre5

**Comment by jackietian** [comment]
The $$hashKey error still pop up using ui router 0.1.0-pre5.

the error is triggered by this line, when depth = -1 and tDataStack.length = 0

Line 1724 var tData = angular.extend(tDataStack[depth], {

so I add another condition in the guard code:

Line 1720 if (transitionDepth >= tDataStack.length || transitionDepth === -1) return; 

not sure of any side effects.

Waiting for comments

Versions:

angular-permission: 1.1.1
ui-router-extras: 0.1.0-pre5

**Comment by christopherthielen** [comment]
Can you set up a demonstration plunk with extras and permissions for me? Use the released version of extras which is 0.1.0.

**Comment by jackietian** [comment]
http://plnkr.co/edit/eSEzPS?p=preview

the error will happen when click the link

**Comment by Teklinski** [comment]
@christopherthielen the problem is here:

```javascript
          $rootScope.$on("$stateChangeStart", function (evt, toState, toParams, fromState, fromParams) {
              if (transitionDepth >= tDataStack.length) return;
              var depth = transitionDepth;
              // To/From is now normalized by ui-router.  Add this information to the transition data object.
              var tData = angular.extend(tDataStack[depth], {
                to: { state: toState, params: toParams },
                from: { state: fromState, params: fromParams }
              });

              var restoreFn = decorateInjector(tData);
              restoreFnStack[depth] = restoreFn;
              $rootScope.$broadcast("$transitionStart", tData);
            }
          );
```

specially in line 
```javascript
var tData = angular.extend(tDataStack[depth], {
```
because ```depth``` is -1 and this value is out of the scope so to extend is passed an undefined. So if you would like to change here:
```javascript
if (transitionDepth >= tDataStack.length) return;
```
to this:
```javascript
if (transitionDepth >= tDataStack.length || transitionDepth < 0) return;
```

will work like a charm.
Best wishes for the New Year!

**Comment by cojack** [comment]
@christopherthielen will you check the solution above?

**Comment by cojack** [comment]
@christopherthielen bump

**Comment by christopherthielen** [comment]
I will get to this when I have the time. I'd be happy to merge a PR

**Comment by PaoolSkoolsky** [comment]
@christopherthielen PR is ready.
