### ISSUE TITLE
[QUESTION][SOLVED] Problem triggering Future States with the url

### ISSUE THREAD

**Issue by mcanovas** [christopherthielen/ui-router-extras#240]
Hello,

I have to trigger a Future State using the url. Meanwhile the ui-router states are working fine, the future states aren't.

I've seen that if I debug the future state code then it is working fine. Then I deduced that it is something related with the callbacks.

The code that I have in the angular config function is:

```
	var resolver = function (Page) {
		Page.all()
			.success(function (data) {
				angular.forEach(data, function (page) {
					$futureStateProvider.futureState({ 
						name: page.name, 
						url: page.url, 
						template: page.template, 
						controller: '', 
						controllerAs: '', 
						type: page.type
					});
				})
			});
	}

	$futureStateProvider.addResolve(resolver);

	var stateFactory = function ($q, futureState) {
		var state = {
			name: futureState.name,
			url: futureState.url,
			template: futureState.template,
			controller: futureState.controller,
			controllerAs: futureState.controllerAs
		};
		return $q.when(state);
	}

	$futureStateProvider.stateFactory('pageFactory', stateFactory);

	$locationProvider.html5Mode(true);
```

Please, Can someone lend me I hand? I'm not able to se what is happening. Meanwhile, I'll continue investigating.

Thanks you so much.

**Comment by mcanovas** [comment]
Ok, I've fixed what is happening.

The resolver function need to return the Page.all() function.

Thank you so much.

**Comment by christopherthielen** [comment]
Always return your promises! :smiley: 
Glad you figured it out.
