### ISSUE TITLE
<state-vis> constantly updates the DOM

### ISSUE THREAD

**Issue by flyer1** [christopherthielen/ui-router-extras#245]
I know this is only a dev tool but I find that the **state-vis** directive (which I love!) is constanting updating the transition values in the DOM, blocking my ability to make changes in the CSS in chrome dev tools (and my CPU is busier than normal). 

To see the issue, if you go to this example: http://christopherthielen.github.io/ui-router-extras/example/sticky/index.html#/ and look at the markup you'll see lines like this constantly changing (the **translate** numbers will be changing, but in such a small way there is no impact visually):

```html
<text class="label" x="112.27272727272728" y="55" text-anchor="middle" style="fill-opacity: 1;" transform="translate(-19.064197810785558,54.0069607348902)rotate(-25)">aside1</text>
```

So I assume some sort of rouding issue is at hand here. I went thru the code for **cd-ui-router-extras.statevis.js** but can't tell if the issue is happening here or it's in **d3**'s tree object. 

Love your repo, followed your discusions with Nate and appreciate knowing the history of how this almost became part of ui-router and then ended up living on it's own.

**Comment by flyer1** [comment]
UPDATE: I noticed that the issue does not occur if I update the **state-vis** directive code to not **rotate the labels**. So if I comment out the "**transform**" line (last line) below then the issue goes away. The text is no longer rotated but in my case my labels are short enough that they don't overlap.
```javascript
          t.selectAll(".label")
            .attr("x", function (d) { return d.px = d.x; })
            .attr("y", function (d) { return d.py = d.y - 15; })
            .attr("transform", function (d) { return "rotate(-25 " + d.x + " " + d.y + ")"; });
```

**Comment by christopherthielen** [comment]
Interesting.  I hardly understand how state-vis works myself.   I'm glad that you found a workaround!

**Comment by christopherthielen** [comment]
I've got a new implementation of statevis in progress over here: 

https://github.com/christopherthielen/new-state-vis/tree/master/app/vis

http://christopherthielen.github.io/new-state-vis/#/app/msgs/123
