### ISSUE TITLE
getting `infdig` when deepStateRedirect use with `$urlRouteProvider.otherwise`

### ISSUE THREAD

**Issue by guy-mograbi-at-gigaspaces** [christopherthielen/ui-router-extras#246]
Hi, 

I was trying to give a reasonable default route for my app.. 
following numerous links, for example : http://stackoverflow.com/questions/16793724/otherwise-on-stateprovider reached a code that looks like this : 

```
.config(function ($stateProvider, $urlRouterProvider) {
        $stateProvider

            .state('deploy', {
                url: '/deploy',
                templateUrl: 'views/directives/base_layout.html',
                deepStateRedirect: { default: { state: 'deploy.cloud' } }
            })

            .state('deploy.cloud', {
                url: '/cloud',
                templateUrl: 'views/directives/deploy_layout.html',
                controller: 'DeployLayoutCtrl',
                deepStateRedirect: { default: { state: 'deploy.cloud.generalData' } }
            }, ... );
          
        $urlRouterProvider.otherwise('/deploy');

    })

```

the aim was to redirect `/` to state `deploy` and have state `deploy` redirect to `deploy.cloud` - this way if the default for `deploy` changes, everything remains consistent. 

I was surprised to see that when I go to `localhost:9000` (no path) - i see infinite redirects with error prints of infinite digest until it reaches. 

This does not happen if I remove one of the two or if the `otherwise` points to a state without `deepStateRedirect`. 

I am using angular 1.4.3 and angular-ui-router 0.2.15.

**Comment by joeljeske** [comment]
I am getting this same issue, even with just a single dsr state and an `otherwise`. 

I was able to alleviate this issue by using the function form of the the otherwise function. Similar to 
```js
$urlRouterProvider.otherwise(function($injector, $location) {
  $injector.get('$state').go('deploy');
});
```

Does that work for you?

**Comment by rleemorlang** [comment]
@joeljeske's suggested workaround resolves the issue for me. Thanks!

**Comment by guy-mograbi-at-gigaspaces** [comment]
yup - works for me too.. thanks.
