### ISSUE TITLE
[q] required node version(s) for ui-router-extras

### ISSUE THREAD

**Issue by ZuBB** [christopherthielen/ui-router-extras#252]
Currently if I run `npm install` in my project where your module is used I get

```
...
npm WARN engine ui-router-extras@0.0.13: wanted: {"node":"0.10.10"} (current: {"node":"0.12.7","npm":"2.11.3"})
...
```

However our team did a lots of testing and we believe that this modules works OK with latest versions of 0.10 and 0.12. Is there any strong reason why you stick with `0.10.10`?

**Comment by christopherthielen** [comment]
No reason. I didn't realize I had called out any specific version of node.

**Comment by ZuBB** [comment]
Can I create an MR which would unstick that exact version?

**Comment by christopherthielen** [comment]
a PR would be welcomed

**Comment by ZuBB** [comment]
done https://github.com/christopherthielen/ui-router-extras/pull/253/files
