### ISSUE TITLE
null "locals" property

### ISSUE THREAD

**Issue by realtyjustin** [christopherthielen/ui-router-extras#258]
Getting an error come up, specifically on line 332 of ct-ui-router-extras.sticky.js, where inactiveExiting.locals is null.  Haven't been able to trace the logic to find the actual problem, but perhaps orphans aren't initialized right?

So on state enter, $state.$current.locals is null, and everything breaks.  I'll try to find issue more clearly, unless anyone else has leads.

**Comment by christopherthielen** [comment]
are you using 0.0.15 release?  Can you reproduce this in a plunker?

**Comment by borntorun** [comment]
Hi, I'm getting the same error; I'v create a [plunker](http://embed.plnkr.co/ql2G7S) to reproduce it.

Scenario: a state/view that as an action that cause the reload of itself (with/without different params) 
I'm using v0.1.0
Error: Cannot read property 'globals' of null
at...../ui-router-extras/release/ct-ui-router-extras.js:684:107

**Comment by davincho** [comment]
Hi, I get this error when calling $state.reload() - any chance to merge the pull request referenced here?

**Comment by lalitkapoor** [comment]
+1

**Comment by yppeaxy** [comment]
I am getting this error when calling $state.go($state.$current, null, {reload:true});

"angular-ui-router": "0.2.15",
"ui-router-extras": "0.1.0"

**Comment by laustdeleuran** [comment]
+1

**Comment by xdemocle** [comment]
+1

**Comment by christopherthielen** [comment]
@lalitkapoor @laustdeleuran @xdemocle @realtyjustin @borntorun @PierreReliquet @davincho 
This should be fixed.  I just released version 0.1.1... please try that and report back.

**Comment by borntorun** [comment]
I confirm that the issue is fixed in my use case: [plunker with v0.1.2](http://embed.plnkr.co/xUPyRx/)
