### ISSUE TITLE
sticky DSR state view is being reloaded  on state change

### ISSUE THREAD

**Issue by yunap** [christopherthielen/ui-router-extras#272]
Hi Chris!

Here is a plunker where you can reproduce the problem:
http://plnkr.co/edit/0zoAkQzTL1psHkHOPHMP?p=preview

To reproduce click on "Account" -> "my things" -> "click for modal" 
notice the view and go to a modal substate - click on  "Activate it" or one of the substates of a modal substate "Click for one" or "Click for two"

The background view will now return to a parent state "Account" even though the state-vis tree is still showing all of the same inactive states "app.account.things", "app.account" and "app"
Now exit modal and watch the view return to app.account.things.

I've been stuck with this for a few days now. Thank you for any suggestions here!

**Comment by Jaco-Pretorius** [comment]
+1 for this being an hairy issue.  Any advice on where to start in terms of getting a fix?
