### ISSUE TITLE
Sticky state not retaining parameters

### ISSUE THREAD

**Issue by jvisser** [christopherthielen/ui-router-extras#280]
Sticky state not retaining parameters

I have a tab case where I need state parameters to be saved. The tab that needs saving is marked as sticky. It seems to have been broken with release 0.0.12 (in 0.0.11 this case works).

Example: http://plnkr.co/edit/apgnpvff8GHywrGCBBq7?p=preview

Steps to reproduce:
1. Klik the 'Deeplink' button on top (tab 2 opens with 'Deeplink' as parameter)
2. Klik 'Tab1'
3. Klik 'Tab2'; Now the parameter 'Deeplink' is reset to the default value of 'Default'.

**Comment by christopherthielen** [comment]
As far as I can tell, this is expected behavior in the current release.  Here's what's going on:

- tab2 has a default parameter value of 'Default'
- Click the ui-sref for `tab2`
- UI-Router supplies the default parameter value of 'Default'
- Tab2 state is activated with param value of 'Default'.
- Because params have changed, the tab2 state is reloaded.

I'm not sure what changed in 0.0.12, but the previous behavior sounds incorrect.

This is what I suggest you do:

Add a custom DSR function on the tab1 that redirects, but only if the incoming parameter value is `Default`

http://plnkr.co/edit/Rtou2J2gTivYzXVVacxq?p=preview

```
			.state('dashboard.details.tab2',
					{
						url: '/tab2/{id:string}',
						params: {
							id: 'Default'                       // Parameter 'id' default value
						},
						sticky: true,
						deepStateRedirect: {
						  fn: function($dsr$) { 
						    var toParams = $dsr$.to.params;
						    return ($dsr$.redirect && toParams != null && toParams.id === 'Default');
						  }
						},
```

**Comment by HackPoint** [comment]
`this.$stateProvider
            .state("app.analytics", <ng.ui.IStickyState>{
                url: "/analytics",
                deepStateRedirect: {
                    fn: ($dsr$) => {
                        return false;
                    }
                },
                sticky: true,
                views: {
                    "analytics": {
                        template: `<div ng-show="vm.$state.includes('app.analytics.{{$parent.$parent.$parent.$parent.$parent.tab.defaultName.toLowerCase() }}')" ui-view="{{$parent.$parent.$parent.$parent.$parent.tab.defaultName.toLowerCase()}}"></div>`,
                        controller: "analyticsRoute",
                        controllerAs: "vm"
                    }
                },
                reloadOnSearch: false
            })
            .state("app.analytics.events", <ng.ui.IStickyState>{
                url: "/events?desc&query/:fromLogin?",
                deepStateRedirect: {
                    fn: ($dsr$) => {
                        return false;
                        // var toParams = $dsr$.to.params;
                        // var redirectToParams = $dsr$.redirect.params;
                        // if (angular.equals(toParams, redirectToParams)) return false;
                        // console.log("TO>",  $dsr$.to);
                        // console.log("REDIRECT>", $dsr$.redirect);
                        // return (toParams != null && toParams[""] === 'Default');
                    }
                },
                views: {
                    "events": {
                        template: `<vr-events init-data="$parent.$parent.$parent.$parent.$parent.tab.initData" is-visible="$parent.$parent.$parent.$parent.$parent.tab.isCurrent" container-id="$parent.$parent.$parent.$parent.$parent.tab.id"></vr-events>`,
                        params: {
                            desc: null,
                            query: null
                        }
                    }
                },
                sticky: true,
                reloadOnSearch: false
            })
            .state("app.analytics.alerts", <ng.ui.IStickyState>{
                url: "/alerts?desc&query/:fromLogin?",
                deepStateRedirect: {
                    fn: ($dsr$) => {
                        return false;
                        /*var toParams = $dsr$.to.params;
                        var redirectToParams = $dsr$.redirect.params;
                        if (angular.equals(toParams, redirectToParams)) return false;
                        console.log("TO>",  $dsr$.to);
                        console.log("REDIRECT>", $dsr$.redirect);
                        return (toParams != null && toParams[""] === 'Default');*/
                    }
                },
                views: {
                    "alerts": {
                        template: `<vr-alerts init-data="$parent.$parent.$parent.$parent.$parent.tab.initData" is-visible="$parent.$parent.$parent.$parent.$parent.tab.isCurrent" container-id="$parent.$parent.$parent.$parent.$parent.tab.id"></vr-alerts>`,
                        params: {
                            desc: null,
                            query: null
                        }
                    }
                },
                sticky: true,
                reloadOnSearch: false
            })
            .state("app.analytics.entity", <ng.ui.IStickyState>{
                url: "/entity/:entityType/:entityId",
                views: {
                    "entity": {
                        template: `<vr-entity-page entity-page-data="$parent.$parent.$parent.$parent.$parent.tab.initData.entityPageScopeData"></vr-entity-page>`,
                        params: {
                            entityType: null,
                            entityId: null
                        }
                    }
                },
                sticky: true,
                reloadOnSearch: false
            });

This isn't working return false doesn't work the $state is still doing reload of the state`
