### ISSUE TITLE
What does is mean $stickyState. stateExiting() parameters?

### ISSUE THREAD

**Issue by mervynyang** [christopherthielen/ui-router-extras#298]
I don't understand the 3 parameters: exiting, exitQueue, onExit.
Who can give me an Example? Thanks!

**Comment by christopherthielen** [comment]
`exiting` is the state currently being exited
`exitQueue` is the list of all the states that will be exited
`onExit` is the state's real onExit callback, if it exists

This is deep into the guts of how sticky states works.  The to and from paths are replaced with surrogate paths (use `$stickyStateProvider.enableDebug(true)` to see the real paths and surrogate paths).  These surrogates are set up with onEnter/onExit callbacks such that the normal ui-router code will call them in the right order.
