### ISSUE TITLE
promises in deepStateRedirect.fn

### ISSUE THREAD

**Issue by JonnyVy** [christopherthielen/ui-router-extras#305]
I'm new in Angular, maybe I don't understand something, but when I try to use this code it doesn't work. `
      
      deepStateRedirect:{  
         fn: function($q , $timeout){
             var deferred = $q.defer();
             $timeout(function(){
                 deferred.resolve({state: 'some_state'});
              }, 200);
         deferred.promise.then(function(s){return s;})
        }
     }
`
And when i dont use promise all work well

**Comment by christopherthielen** [comment]
Deep state redirect is synchronous, so you can't use promises. 

UI-Router 1.0 hooks support asynchronous processing.  See https://ui-router.github.io/docs/latest/interfaces/ng1.ng1statedeclaration.html#redirectto
