### ISSUE TITLE
FutureState register order is important?

### ISSUE THREAD

**Issue by ipoly** [christopherthielen/ui-router-extras#314]
In ui-router I can register states in any order.
But in FutureState I need register child state after the parent state has been registered.
If this is a expected behavior?
Thanks.
http://plnkr.co/edit/umUmXgJ7dqu10zz4m1W1?p=preview

**Comment by christopherthielen** [comment]
Yes, future states registration order is important; parent states must be registered before children.

This might change in the future, but for now that's expected.
