### ISSUE TITLE
Sticky states w/ typed parameters

### ISSUE THREAD

**Issue by kasperlewau** [christopherthielen/ui-router-extras#328]
Hiya! I recently posted an issue at ui-router (https://github.com/angular-ui/ui-router/issues/2832) and having played around with the suggested solution I've managed to spawn quite a few errors, unfortunately I haven't come to any conclusion(s).

First, I need to switch around the code in `encode` and `decode` in the [supplied answer]() for the code to compute. 

```js
$urlMatcherFactoryProvider.type('objid', {
  encode: (o) => o,
  decode: (o) => o.id,
  is: (o) => typeof o === 'object',
  equals: (a, b) => a.id === b.id
});
```

As can be seen in this **[jsFiddle](http://jsfiddle.net/6dmtwkkt/1/)**, it appears to **work just fine™!**

---

However, this will _not_ work if I add `sticky: true` to the parameterized state. 

If `sticky: true` is added to the state with a parameterized URL, I can enter it once but on reactivation an error will be thrown. 

![err](https://i.imgur.com/9BBgIG8.png)

**[jsFiddle (broken)](http://jsfiddle.net/rmgetsrm/1/)**

--- 

Now, if I pass some parameters when going to the state: 

```js
const feed = { id: 'feed-3804yuhnsdf-234u80' };
const item { id: 'item-29u3804hueonjsdm' };
const params = { feed, item };
$state.go('foo', params);
```

The `onEnter` function is called with an odd looking set of params: 

![onEnter](https://i.imgur.com/ld1FvjW.png)

So it would seem that the `encode/decode` functionality needs some love at this point (i.e. going back to something that looks a lot more like what @christopherthielen suggested in the above linked ui-router issue). 

```js
$urlMatcherFactoryProvider.type('objid', {
  encode: (o) => '' + o.id,
  decode: (str) => str,
  is: (o) => typeof o === 'object',
  equals: (a, b) => a.id === b.id
});
```

**[jsFiddle (final)](http://jsfiddle.net/2fyf7mz2/1/)**

At this point, it _seems_ to be fine but: 

1. You cannot transition from `foo(with params)  -> foo(without params)`. I suppose this is just the default behaviour. 
2. You cannot transition from `home -> foo(with params) -> home -> foo(without params)`. This will throw the following: 

![err](https://i.imgur.com/2fcnjZk.png)

--- 

I ended up with something like this in the very end: 

```js
$urlMatcherFactoryProvider.type('objid', {
  encode: (o) => {
     return '' + (o ? o.id : '');
  },
  decode: (str) => {
    return { id: '' + (str.id || str) };
  },
  is: (o) => typeof o === 'object',
  equals: (a,b) => {
    a = a || {};
    b = b || {};

    return a.id === b.id;
  }
});
```

**[jsFiddle](http://jsfiddle.net/w79gLcq7/)**

With the added guards in `equals`, `encode` and `decode` I can successfully transition between sticky states with typed parameters & default values. 

It does feel as if this can be cleaned up vastly, and the errors are slightly worrying to me. It's probably the case of me not groking typed parameters correctly - but the majority of the issues experienced occured as I added `sticky: true` to my state definition.

I suppose my question is this: Are there any known gotchas with sticky states and typed parameters?

**Comment by christopherthielen** [comment]
> I suppose my question is this: Are there any known gotchas with sticky states and typed parameters?

As of version 0.1.0, sticky states are supposed to understand parameters, including typed parameters: https://github.com/christopherthielen/ui-router-extras/blob/master/src/stickyProvider.js#L107-L108

See this issue: https://github.com/christopherthielen/ui-router-extras/issues/239

**Comment by christopherthielen** [comment]
> You cannot transition from foo(with params) -> foo(without params). I suppose this is just the default behaviour.

Try using `<a ui-sref="tostate({})" ui-sref-opts="{ inherit: false }">`.  You may be seeing the default `inherit: true` behavior, where a transition inherits the previous parameter values.

> You cannot transition from home -> foo(with params) -> home -> foo(without params). This will throw the following:

In your .equals method, you are responsible for checking for nulls, undefined, etc, so I think your last version of `.equals` is fine.
