### ISSUE TITLE
Controllers Running Multiple Times With Sticky States and Adding/Removing Tabs

### ISSUE THREAD

**Issue by aaronpikkarainen** [christopherthielen/ui-router-extras#331]
Greetings!

My team has found an issue where controllers are running multiple times when using sticky states, $stickyState.reset, and adding/removing tabs. The issue is demonstrated in the below Plunker...

https://plnkr.co/edit/HJ3tfvl0DuETnDmGD7NP?p=preview

Steps:
1. Open the developer console
2. Click the 'Add Tab' button (this adds a tab to DOM and goes to the account state tree)
3. Click the 'Remove Tab' button (removes DOM, $stickyState.reset, and goes to survey state)
4. Click the 'Add Tab' button (this again goes to the account state tree)
    **- See in the console that the Account controllers are running twice. Repeating these steps results in them running three times, etc.**

This is a critical issue for my team, so we're hoping to get a fix for it. Thank you!

_Note: This example is using version 0.2.18, but you can see it with 0.3.1 too, however there's an odd bug in that version with a 'Cannot read property '$$animLeave' of undefined' console error._

**Comment by aaronpikkarainen** [comment]
Another note on this that may help to find the issue...

If the line _$stickyState.reset('account');_ is **not** called, then the controllers only run once, which is good (however when reset is not called, other major issues show up, so it's essential). So there must be an issue in that reset method or in some other code that is affected by the reset method.

My team has a very large app, and this is a blocker issue for us, so your work on it is greatly appreciated!

**Comment by albertonaperijr** [comment]
+1

**Comment by dcurletti** [comment]
I'm having a very similar issue.  I followed the Pinterest example and everything is working fine, except that my Modal state calls `ngDialog` to open another modal.  When that second modal is created, everytime I navigate back to the modal, the controller runs twice.

**Comment by christopherthielen** [comment]
@aaronpikkarainen The problem you run into is because you remove the DOM without informing angular.


If you're going to mess with angular at this level, you need to be very careful.  I changed your code to create child scopes when compiling, and to destroy the scopes when removing the DOM:

```js
  scope.addTab = function () {
           var tab = $compile('<li id="new-tab" ui-sref="account" ui-sref-active="selected">Account</li>')(scope.$new());  // HERE
           element.find('ul').append(tab);
           
           var tabPanel = $compile('<div id="new-tab-panel" ng-show="$state.includes(\'account\')"><div ui-view="account"></div></div>')(scope.$new());  // HERE
           element.append(tabPanel);
           
           $state.go('account');
         };
         
         scope.removeTab = function () {
           $state.go('survey');
     
           // Remove tab's DOM
           var tab = element.find('#new-tab');
           angular.element(tab).scope().$destroy(); // HERE
           tab.remove();
           
           var tabPanel = element.find('#new-tab-panel');
           angular.element(tabPanel).scope().$destroy();  // HERE
           tabPanel.remove();
```

https://plnkr.co/edit/4gljf61wlIL9ZkOnrzCN?p=preview

**Comment by aaronpikkarainen** [comment]
That worked! Thank you so much for your help with this, especially showing how we can modify our code to fix it. This is a great relief for my team. The angular ui router continues to prove to be amazing.
