### ISSUE TITLE
Compatibility with ui-router version 0.3.1

### ISSUE THREAD

**Issue by kyleholzinger** [christopherthielen/ui-router-extras#333]
Hi! Do you know if the `angular-ui-router` version 0.3.1 is supported? I've ran the specs on that version as well and it passed all of them, but I was just wondering if there was a specific reason why you stopped at 0.2.8.

**Comment by christopherthielen** [comment]
0.2.8 version reference is just an oversight.  Extras should be fully compatible with 0.3.1!

**Comment by kyleholzinger** [comment]
Wonderful, thank you!
