### ISSUE TITLE
FutureState: Promise rejected on successful transition (plunkr provided)

### ISSUE THREAD

**Issue by jdmichaud** [christopherthielen/ui-router-extras#338]
When calling `$state.go('someState');` on a futureState `someState`, the return promise fails even though the state is properly loaded.
It seems to be due to the `event.preventDefault();` in `$stateNotFound` event handler:

>     * - 'transition aborted' - when `event.preventDefault()` has been called in a `$stateNotFound` listener or
>     *   when a `$stateNotFound` `event.retry` promise errors.

Plunkr here: https://plnkr.co/edit/3FvvL5eANYqTnx9oxO8C

Click on Top state and look in the developer console: it prints `transition failed`. From what I understand it shouldn't.
I need to perform some action on transition failure and hooking to the `$stateChangeError` will be a pain because other places will change state and I don't want to handle their failures. Also I need some closure from the function calling `$state.go`.

**Comment by jdmichaud** [comment]
Can anyone confirm this issue?

**Comment by christopherthielen** [comment]
If I remember correctly, the initial transition is cancelled while waiting for the future state to load, then a new transition is started

**Comment by christopherthielen** [comment]
note: future states are in ui-router core in 1.0.0-beta.2 now
