### ISSUE TITLE
Force reload causes push error on non-array variable

### ISSUE THREAD

**Issue by RobbSadler** [christopherthielen/ui-router-extras#339]
In ct-ui-router-extras.js: 
The line below is used to force reload by adding a param to the watched params, however, this params variable is a javascript object, not an array and the push command causes an exception.

if (reloadStateTree) {
...
                  params.push('$$uirouterextrasreload');

using ui-router 0.2.18

**Comment by christopherthielen** [comment]
This should be guarded by the version heuristics.  Are you using latest ui-router-extras release?

```
                if (versionHeuristics.hasParamSet) {
                  var tempParam = new $urlMatcherFactoryProvider.Param('$$uirouterextrasreload');
                  params.$$uirouterextrasreload = ownParams.$$uirouterextrasreload = tempParam;
                  restore.restoreFunctions.push(function() {
                    delete params.$$uirouterextrasreload;
                    delete ownParams.$$uirouterextrasreload;
                  });
                } else {
                  params.push('$$uirouterextrasreload');
                  ownParams.push('$$uirouterextrasreload');
                  restore.restoreFunctions.push(function() {
                    params.length = params.length -1;
                    ownParams.length = ownParams.length -1;
                  });
                }
```

**Comment by RobbSadler** [comment]
using version 0.1.2 - it is coming into this block of code with params == { }

**Comment by christopherthielen** [comment]
it's OK that `params == { }`... 
In your case with 0.2.18 the `versionHeuristics.hasParamSet` should be true, so the top block  should be invoked, not the bottom one.

**Comment by RobbSadler** [comment]
Thanks for the response.

OK, I double checked the ui-router version. Turns out that the bower_components version is not getting loaded, but instead one that was in the template we started with. I will update and re-check.

**Comment by RobbSadler** [comment]
OK, I rewired the ui-router to pull the latest (0.2.18, that I thought it was doing in the first place), and it now behaves.

Thanks for the input, Christopher!
