### ISSUE TITLE
StickyState doesn't support parent named ui-view replacement

### ISSUE THREAD

**Issue by yopif** [christopherthielen/ui-router-extras#343]
I am using stickyState to pop a modal from a state that replace it's parent view. Then on the modal when going the modal's sub-state, the view in the background is replaced by the parent of the state on witch i called the modal, it's a little bit tricky so i reproduce the bug on the example plnkr : http://plnkr.co/edit/We0Nx1NyvFTBmPuek7as?p=preview  ( go deep into app.account.myStuff  then open the modal and it's substate)

**Comment by olivierloverde** [comment]
+1

**Comment by DORIAN-AQ** [comment]
+1

**Comment by Chupsy** [comment]
+1

**Comment by Deftunk** [comment]
+1

**Comment by tcouloumy** [comment]
+1

**Comment by SomeKittens** [comment]
Rather than getting all your coworkers to +1, how's about submitting a pull request?

**Comment by christopherthielen** [comment]
http://plnkr.co/edit/vzsCMwGmUW7qtozJ4z1X?p=preview

**Comment by yopif** [comment]
Thank you
