### ISSUE TITLE
Question: in ui-sref It is possible to do $stickyState.reset()

### ISSUE THREAD

**Issue by nahuelramos** [christopherthielen/ui-router-extras#347]
Hi i have a menu with different sticky states, I need that when click run $stickyState.reset().
![github](https://cloud.githubusercontent.com/assets/22099152/19893434/eb0e437c-a027-11e6-8318-66540361fe68.png)

**Comment by christopherthielen** [comment]
`<a ui-sref="home" ng-click="reset('home')">Home</a>`

Then implement `reset` in a controller.
