### ISSUE TITLE
Does ui-router-extras work with Angular 2?

### ISSUE THREAD

**Issue by ProgPoint** [christopherthielen/ui-router-extras#349]

**Comment by christopherthielen** [comment]
No.  But some of the features of UI-Router Extras are available for ui-router-ng2, or are being worked on.

Future states are baked into ui-router 1.0 (and ui-router-ng2)

Deep State Redirect is re-written for 1.0 and I will publish it when sticky states are ready: https://github.com/christopherthielen/deep-state-redirect  it will remain as a separate project.  

Sticky States is in process of being re-written for 1.0 and it will be a new project.

UI-Router Extras will be only for angular 1 and will only work on the 0.X "legacy" versions.
