### ISSUE TITLE
$state.go not does not return the promise (FutureState)

### ISSUE THREAD

**Issue by nahuelramos** [christopherthielen/ui-router-extras#350]
```
$futureStateProvider.futureState(newFutureState);
 $state.go(newFutureState.name).then(function(data){
Never enter by then
}).catch(function(data){
Error here (Image of console.log)
});
```
![image error](https://cloud.githubusercontent.com/assets/22099152/20305833/30e3fb28-ab16-11e6-920c-8e7f26491a9d.png)

But The transition occurs satisfactorily.

**Comment by christopherthielen** [comment]
Agreed, this would be really nice.  Unfortunately it's not possible in the Future States architecture.  The future state code listens for the `$stateNotFound` event, which is emitted when you go to `newFutureState.name` which doesn't exist. That promise must always be rejected for the not found event to fire.  A new `$state.go()` is run after the future state is loaded.

In ui-router 1.0 (which has future states baked in), this works as you expect.  The promise returned from `$state.go()` resolves after the future state is loaded and transitioned to.
