### ISSUE TITLE
Issue with sticky states replacing parent view

### ISSUE THREAD

**Issue by davecranwell** [christopherthielen/ui-router-extras#353]
http://plnkr.co/edit/FZj3bMlFPNtSTn0pNr9d?p=preview

I'm pretty sure this is something obvious I'm missing, but I can't seem to get this to work. 

I've got a named view, in which I load more views which I want to be sticky, but swapping to those views only seems to override the parent.

What have I done wrong here?

**Comment by bvallambhotla** [comment]
Seems, you configured the child routes without a parent.

.state('newViewTest1') instead of .state('test.newViewTest1')

Here is the updated plnkr:
http://plnkr.co/edit/bh1zJU?p=preview

Hope this is what you are trying to do and this helps.

**Comment by davecranwell** [comment]
Thanks for your reply. It's clear to me now by reduced case was not actually representative of what I was trying to achieve.

I've updated the plnkr from before. 

In reality the situation is that I have a `sideView` as a _sibling_ of my `mainView`, at the root of the app DOM, which modules can choose to use how they wish.

My intent is that I can have multiple routing configurations e.g one per module, that can optionally add content into the 'sideView' without requiring URLs for those states. The 'sideView' is an unimportant pop-out which should not require URL/location changes, but should be accessible by any module I choose to bolt on.

Have I just misunderstood what Sticky states can accomplish here? Is this achievable without them?
