### ISSUE TITLE
Code doesn't uglify properly

### ISSUE THREAD

**Issue by GuyPie** [christopherthielen/ui-router-extras#38]
My project combines all scripts and uglifies them on deployment, but this code causes error when uglified. I think it's because not all angular injections are done using the array notation.

**Comment by fabricioflores** [comment]
I'm using gulp and have the same issue... did you find a solution?

**Comment by christopherthielen** [comment]
are you using ng-annotate via gulp?

**Comment by fabricioflores** [comment]
Yes, I'm using gulp, ng-annotate and uglify

**Comment by christopherthielen** [comment]
This was confirmed as an ng-annotate bug, make sure you're using a recent version.

View this ng-annotate issue: https://github.com/olov/ng-annotate/issues/82

**Comment by fabricioflores** [comment]
Yes, I'm using lastest version. ng-annotate@0.15.4 gulp-ng-annotate@0.5.2 and gulp-uglify@1.1.0

**Comment by kwieckowski-neducatio** [comment]
Same issue here with grunt-ng-annotate@0.10.0 and ng-annotate@0.15.4 

Sticky states doesn't seem to work at all and I'm getting 'Cannot read property 'self' of undefined' message in debugging mode.

**Comment by FlyingDeveloper** [comment]
This was a problem for me - I bumped to `ng-annotate#1.0.1` and that fixed it

**Comment by jmartinezuk** [comment]
i'm still having issues with this. everything is up to date, but router extras (or ui-router when used with router extras) fails when using  uglify and mangle:true
