### ISSUE TITLE
DeepStateRedirect for states with parameters

### ISSUE THREAD

**Issue by readme42** [christopherthielen/ui-router-extras#64]
Take the following state definition

``` javascript
.state('person', {
    url : '/person/:person_id',
    controller: 'PersonDetailsCtrl',
    templateUrl: 'templates/record/record.html',
    deepStateRedirect : true
})
```

My goal was switching between different persons and keeping their state context saved. But this does not work. With `deepStateRedirect` enabled, the browser url is **not** updated if switched between different persons like `/person/123` and `/person/445`

If the first opened person was `/person/123[/anything/else]`, there is no chance to open `/person/445` - the url will switch back to `/person/123[/anything/else]` automatically.

**Comment by readme42** [comment]
I think we should document [this new syntax](https://github.com/christopherthielen/ui-router-extras/issues/64#issuecomment-61540847) into [that](http://christopherthielen.github.io/ui-router-extras/#/dsr)

**Comment by christopherthielen** [comment]
@readme42 yes, they're in gh-pages branch.  Would love a PR for docs!
