### ISSUE TITLE
Triggering a default sticky state on modal deep link

### ISSUE THREAD

**Issue by fr1n63** [christopherthielen/ui-router-extras#93]
I've been banging my head against this for a few days, hoping I was just being stupid, it's still a possibility but I'm out of ideas. Anyway, you can see the issue directly on your example... Deep link to here...

http://christopherthielen.github.io/ui-router-extras/example/stickymodal/index.html#/modal1

The modal opens, but in the background the sticky state is unpopulated. I'm attempting to use the stickymodal for a more complex, nested sidebar, so it is desirable to be able to link to the page with the sidebar in a specific state.

I have been using the following pseudocode in a controller to trigger the default state on first load, which sort of works...
```
$scope.$on('$stateChangeSuccess', function(){
var isModalState = $state.includes(modalState);
var noInactiveStates = $stickyStateProvider.getInactiveStates().length === 0;

if (isModalState && noInactiveStates)
            {
                $state.transitionTo(defaultState, $stateParams, {
                    location: false,
                    inherit : true,
                    relative: $state.$current,
                    notify  : true
                });
            }
});
```
I say it works, it makes 3 transitions, first to its intended state, then to its default state, and finally a third one back again. I have no idea why it makes the third transition, it wasn't requested, but it drops the app in the desired state with everything displaying correctly, feels like a happy bug....

However if I have this modal/sticky group as a nested state, and I navigate out of the parent state and back again. This whole operation only triggers twice, leaving me in the default state, but the url is now mis-matched.

Is there any way to trigger a state in an inactive starting position, silently? So I could avoid the multiple state changes, which are most likely incorrect.

**Comment by christopherthielen** [comment]
If you have additional questions, feel free to reopen for discussion.

**Comment by christopherthielen** [comment]
http://plnkr.co/edit/rIxTa9DyOB2jsk8lpE1h?p=preview
